/*
 * Copyright (c) 2000-2002, Shayne R Flint
 * All rights reserved.
 * 
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *    * Redistributions of source code must retain the above copyright
 *      notice, this list of conditions and the following disclaimer.
 *
 *    * Redistributions in binary form must reproduce the above copyright
 *      notice, this list of conditions and the following disclaimer in the
 *      documentation and/or other materials provided with the distribution.
 *
 *    * The name of the author may not be used to endorse or promote products
 *      derived from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
 * IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
 * OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
 * IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
 * NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
 * THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/*
 * ./armidale/api/gui/impl/platform/swing/BorderPanelImpl.java
 * Generated by armidale.utilities.makeclass.Main armidale v0.9.5 on 10Apr2002 at 17:58:07
 *
 */

package armidale.api.gui.impl.platform.swing;

  import armidale.api.context.*;
  import armidale.api.gui.BorderPanel;
  import armidale.api.gui.BorderPanelWidget;
  import armidale.api.gui.impl.platform.swing.PanelImpl;
  //--ARM-- imports
  import javax.swing.JPanel;
  import javax.swing.JComponent;
  import java.awt.BorderLayout;
  import armidale.api.gui.Widget;
  //--ARM-- imports

public class BorderPanelImpl extends PanelImpl implements BorderPanel {

  //--ARM-- declarations
  //--ARM-- declarations

  public BorderPanelImpl() {
    //--ARM-- constructor()
    ((JPanel) peer).setLayout(new BorderLayout());
    //--ARM-- constructor()
    setHorizontalGap(DEFAULT_HORIZONTALGAP);
    setVerticalGap(DEFAULT_VERTICALGAP);
    //--ARM-- constructor() - end
    //--ARM-- constructor() - end
  }

  protected void setPeer() {
    //--ARM-- setPeer()
    peer = new JPanel();
    //--ARM-- setPeer()
  }

  // set/get/is methods
  //

  public int getHorizontalGap() {
    //--ARM-- public int getHorizontalGap()
    return ((BorderLayout) ((JPanel) peer).getLayout()).getHgap();
    //--ARM-- public int getHorizontalGap()
  }

  public void setHorizontalGap(int horizontalGap) {
    //--ARM-- public void setHorizontalGap(int horizontalGap)
    ((BorderLayout) ((JPanel) peer).getLayout()).setHgap(horizontalGap);
    //--ARM-- public void setHorizontalGap(int horizontalGap)
  }

  public int getVerticalGap() {
    //--ARM-- public int getVerticalGap()
    return ((BorderLayout) ((JPanel) peer).getLayout()).getVgap();
    //--ARM-- public int getVerticalGap()
  }

  public void setVerticalGap(int verticalGap) {
    //--ARM-- public void setVerticalGap(int verticalGap)
    ((BorderLayout) ((JPanel) peer).getLayout()).setVgap(verticalGap);
    //--ARM-- public void setVerticalGap(int verticalGap)
  }

  // other methods
  //

  public void addWidget(BorderPanelWidget borderPanelWidget) {
    //--ARM-- public void addWidget(BorderPanelWidget borderPanelWidget)
    Widget  theWidget       = borderPanelWidget.getWidget();
    int     theConstraints  = borderPanelWidget.getConstraint();
    if (theWidget != null) {
      switch (theConstraints) {
        case BorderPanelWidget.NORTH:
          ((JPanel) peer).add((JComponent) ((WidgetImpl)theWidget).peer, BorderLayout.NORTH);
          break;
        case BorderPanelWidget.SOUTH:
          ((JPanel) peer).add((JComponent) ((WidgetImpl)theWidget).peer, BorderLayout.SOUTH);
          break;
       case BorderPanelWidget.EAST:
          ((JPanel) peer).add((JComponent) ((WidgetImpl)theWidget).peer, BorderLayout.EAST);
          break;
       case BorderPanelWidget.WEST:
          ((JPanel) peer).add((JComponent) ((WidgetImpl)theWidget).peer, BorderLayout.WEST);
          break;
        case BorderPanelWidget.CENTER:
          ((JPanel) peer).add((JComponent) ((WidgetImpl)theWidget).peer, BorderLayout.CENTER);
          break;
      }
    }
    //--ARM-- public void addWidget(BorderPanelWidget borderPanelWidget)
  }


  public void removeWidget(BorderPanelWidget borderPanelWidget) {
    //--ARM-- public void removeWidget(BorderPanelWidget borderPanelWidget)
    Widget     theWidget    = borderPanelWidget.getWidget();
    JComponent theComponent = (JComponent) ((WidgetImpl)theWidget).peer;
    ((JPanel)peer).remove(theComponent);
    //--ARM-- public void removeWidget(BorderPanelWidget borderPanelWidget)
  }


  public void removeAllWidgets() {
    //--ARM-- public void removeAllWidgets()
    ((JPanel) peer).removeAll();
    //--ARM-- public void removeAllWidgets()
  }

}
