/*
 * Copyright (c) 2000-2002, Shayne R Flint
 * All rights reserved.
 * 
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *    * Redistributions of source code must retain the above copyright
 *      notice, this list of conditions and the following disclaimer.
 *
 *    * Redistributions in binary form must reproduce the above copyright
 *      notice, this list of conditions and the following disclaimer in the
 *      documentation and/or other materials provided with the distribution.
 *
 *    * The name of the author may not be used to endorse or promote products
 *      derived from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
 * IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
 * OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
 * IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
 * NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
 * THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/*
 * ./armidale/api/gui/impl/platform/swing/FrameImpl.java
 * Generated by armidale.utilities.makeclass.Main armidale v0.9.5 on 10Apr2002 at 17:58:26
 *
 */

package armidale.api.gui.impl.platform.swing;

  import armidale.api.context.*;
  import armidale.api.gui.Color;
  import armidale.api.gui.Frame;
  import armidale.api.gui.Image;
  import armidale.api.gui.MenuBar;
  import armidale.api.gui.Position;
  import armidale.api.gui.Size;
  import armidale.api.gui.Widget;
  import armidale.api.gui.constants.Compass;
  import armidale.api.gui.impl.platform.swing.WindowImpl;
  //--ARM-- imports
import javax.swing.JFrame;
import javax.swing.JMenuBar;
import javax.swing.JComponent;
import javax.swing.ImageIcon;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.Component;
import java.awt.Container;
import javax.swing.WindowConstants;
  //--ARM-- imports

public class FrameImpl extends WindowImpl implements Frame {

  //--ARM-- declarations
  private    WidgetImpl          statusbar;
  private    MenuBarImpl         menubar;
  private    WidgetImpl          toolbar;
  private    WidgetImpl          content;
  private    ImageImpl           icon;

  private class SwingFrameListener implements java.awt.event.WindowListener {
    public void windowActivated(java.awt.event.WindowEvent e) {
      windowCallbackList.windowActivated(FrameImpl.this);
    }

    public void windowClosed(java.awt.event.WindowEvent e) {
      windowCallbackList.windowClosed(FrameImpl.this);
    }

    public void windowClosing(java.awt.event.WindowEvent e) {
      windowCallbackList.windowClosing(FrameImpl.this);
    }

    public void windowDeactivated(java.awt.event.WindowEvent e) {
      windowCallbackList.windowDeactivated(FrameImpl.this);
    }

    public void windowDeiconified(java.awt.event.WindowEvent e) {
      windowCallbackList.windowDeiconified(FrameImpl.this);
    }

    public void windowIconified(java.awt.event.WindowEvent e) {
      windowCallbackList.windowIconified(FrameImpl.this);
    }

    public void windowOpened(java.awt.event.WindowEvent e) {
      windowCallbackList.windowOpened(FrameImpl.this);
    }
  }

  public void show() {
    ((JFrame)peer).pack();
    super.show();
  }
  
  public void dispose() {
    ((JFrame)peer).dispose();
  }
 
  //--ARM-- declarations

  public FrameImpl() {
    //--ARM-- constructor()
    //--ARM-- constructor()
    setSize(DEFAULT_SIZE);
    setPosition(DEFAULT_POSITION);
    setResizable(DEFAULT_RESIZABLE);
    setTitle(DEFAULT_TITLE);
    setBackgroundColor(DEFAULT_BACKGROUNDCOLOR);
    //--ARM-- constructor() - end
    ((JFrame)peer).addWindowListener(new SwingFrameListener());
    ((JFrame)peer).setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
    //--ARM-- constructor() - end
  }

  protected void setPeer() {
    //--ARM-- setPeer()
    peer = new JFrame();
    hide();
    //--ARM-- setPeer()
  }

  // set/get/is methods
  //

  public Size getSize() {
    //--ARM-- public Size getSize()
    return Conversions.size(((JFrame) peer).getSize());
    //--ARM-- public Size getSize()
  }

  public void setSize(Size size) {
    //--ARM-- public void setSize(Size size)
    ((JFrame) peer).setSize(Conversions.awtDimension(size));
    //--ARM-- public void setSize(Size size)
  }

  public Position getPosition() {
    //--ARM-- public Position getPosition()
    return Conversions.position(((JFrame) peer).getLocation());
    //--ARM-- public Position getPosition()
  }

  public void setPosition(Position position) {
    //--ARM-- public void setPosition(Position position)
    ((JFrame) peer).setLocation(position.getX(), position.getY());
    //--ARM-- public void setPosition(Position position)
  }

  public boolean isResizable() {
    //--ARM-- public boolean isResizable()
    return ((JFrame) peer).isResizable();
    //--ARM-- public boolean isResizable()
  }

  public void setResizable(boolean resizable) {
    //--ARM-- public void setResizable(boolean resizable)
    ((JFrame) peer).setResizable(resizable);
    //--ARM-- public void setResizable(boolean resizable)
  }

  public String getTitle() {
    //--ARM-- public String getTitle()
    return ((JFrame) peer).getTitle();
    //--ARM-- public String getTitle()
  }

  public void setTitle(String title) {
    //--ARM-- public void setTitle(String title)
    ((JFrame) peer).setTitle(title);
    //--ARM-- public void setTitle(String title)
  }

  public Widget getContent() {
    //--ARM-- public Widget getContent()
    return content;
    //--ARM-- public Widget getContent()
  }

  public void setContent(Widget content) {
    //--ARM-- public void setContent(Widget content)
    this.content = (WidgetImpl) content;
    this.content.setPreferredSize(this.getSize());

      ((JFrame) peer).getContentPane().add((JComponent)this.content.peer, BorderLayout.CENTER);
      ((JFrame)peer).pack();
    //--ARM-- public void setContent(Widget content)
  }

  public Image getIcon() {
    //--ARM-- public Image getIcon()
    return icon;
    //--ARM-- public Image getIcon()
  }

  public void setIcon(Image icon) {
    //--ARM-- public void setIcon(Image icon)
    ImageImpl imageImpl;
    ImageIcon imageIcon;
    java.awt.Image     image;
    if (icon != null) {
      this.icon = (ImageImpl)icon;
      imageImpl = (ImageImpl)icon;
      imageIcon = (ImageIcon)imageImpl.peer;
      image     = imageIcon.getImage();
      ((JFrame) peer).setIconImage(image);
    }
    //--ARM-- public void setIcon(Image icon)
  }

  public MenuBar getMenubar() {
    //--ARM-- public MenuBar getMenubar()
    return menubar;
    //--ARM-- public MenuBar getMenubar()
  }

  public void setMenubar(MenuBar menubar) {
    //--ARM-- public void setMenubar(MenuBar menubar)
    this.menubar = (MenuBarImpl) menubar;
    if (menubar != null) {
      ((JFrame) peer).setJMenuBar((JMenuBar) this.menubar.peer);
    }
    //--ARM-- public void setMenubar(MenuBar menubar)
  }

  public Widget getToolbar() {
    //--ARM-- public Widget getToolbar()
    return toolbar;
    //--ARM-- public Widget getToolbar()
  }

  public void setToolbar(Widget toolbar) {
    //--ARM-- public void setToolbar(Widget toolbar)
    this.toolbar = (WidgetImpl) toolbar;
    if (toolbar != null) {
      ((JFrame) peer).getContentPane().add((JComponent) this.toolbar.peer, BorderLayout.NORTH);
    }
    //--ARM-- public void setToolbar(Widget toolbar)
  }

  public Widget getStatusbar() {
    //--ARM-- public Widget getStatusbar()
    return statusbar;
    //--ARM-- public Widget getStatusbar()
  }

  public void setStatusbar(Widget statusbar) {
    //--ARM-- public void setStatusbar(Widget statusbar)
    this.statusbar = (WidgetImpl) statusbar;
    if (statusbar != null) {
      ((JFrame) peer).getContentPane().add((JComponent) this.statusbar.peer, BorderLayout.SOUTH);
    }
    //--ARM-- public void setStatusbar(Widget statusbar)
  }

  public Color getBackgroundColor() {
    //--ARM-- public Color getBackgroundColor()
    return Conversions.color(((JFrame) peer).getBackground());
    //--ARM-- public Color getBackgroundColor()
  }

  public void setBackgroundColor(Color backgroundColor) {
    //--ARM-- public void setBackgroundColor(Color backgroundColor)
    ((JFrame) peer).setBackground(Conversions.awtColor(backgroundColor));
    //--ARM-- public void setBackgroundColor(Color backgroundColor)
  }

  // other methods
  //

  public void setAlignment(float xAlign, float yAlign) {
    //--ARM-- public void setAlignment(float xAlign, float yAlign)
    Dimension  parentSize  = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
    Dimension  size;
    size = ((JFrame) peer).getSize();
    int        xPos        = (int) ((float) (parentSize.width - size.width) * xAlign);
    int        yPos        = (int) ((float) (parentSize.height - size.height) * yAlign);
    setPosition(new Position(xPos, yPos));
    //--ARM-- public void setAlignment(float xAlign, float yAlign)
  }


  public void setAlignment(int alignment) {
    //--ARM-- public void setAlignment(int alignment)
    switch (alignment) {
      case NORTH:
        setAlignment(0.5f, 0.0f);
        break;
      case NORTH_EAST:
        setAlignment(1.0f, 0.0f);
        break;
      case EAST:
        setAlignment(1.0f, 0.5f);
        break;
      case SOUTH_EAST:
        setAlignment(1.0f, 1.0f);
        break;
      case SOUTH:
        setAlignment(0.5f, 1.0f);
        break;
      case SOUTH_WEST:
        setAlignment(0.0f, 1.0f);
        break;
      case WEST:
        setAlignment(0.0f, 0.5f);
        break;
      case NORTH_WEST:
        setAlignment(0.0f, 1.0f);
        break;
      case CENTER:
        setAlignment(0.5f, 0.5f);
        break;
    }
    //--ARM-- public void setAlignment(int alignment)
  }

}
