/*
 * Copyright (c) 2000-2002, Shayne R Flint
 * All rights reserved.
 * 
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *    * Redistributions of source code must retain the above copyright
 *      notice, this list of conditions and the following disclaimer.
 *
 *    * Redistributions in binary form must reproduce the above copyright
 *      notice, this list of conditions and the following disclaimer in the
 *      documentation and/or other materials provided with the distribution.
 *
 *    * The name of the author may not be used to endorse or promote products
 *      derived from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
 * IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
 * OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
 * IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
 * NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
 * THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/*
 * ./armidale/api/gui/impl/platform/swing/GridPanelWidgetImpl.java
 * Generated by armidale.utilities.makeclass.Main armidale v0.9.5 on 10Apr2002 at 17:58:30
 *
 */

package armidale.api.gui.impl.platform.swing;

  import armidale.api.context.*;
  import armidale.api.gui.GridPanelWidget;
  import armidale.api.gui.Insets;
  import armidale.api.gui.Widget;
  import armidale.api.gui.constants.Compass;
  import armidale.api.gui.constants.FillMode;
  import armidale.api.gui.constants.GridCell;
  import armidale.api.impl.platform.swing.ArmidaleObjectImpl;
  //--ARM-- imports
  //--ARM-- imports

public class GridPanelWidgetImpl extends ArmidaleObjectImpl implements GridPanelWidget {

  //--ARM-- declarations
  Widget widget;
  int    gridX;
  int    gridY;
  int    gridWidth;
  int    gridHeight;
  float  weightX;
  float  weightY;
  int    anchor;
  int    fill;
  Insets insets;
  int    internalPadX;
  int    internalPadY;
  //--ARM-- declarations

  public GridPanelWidgetImpl() {
    //--ARM-- constructor()
    //--ARM-- constructor()
    setGridWidth(DEFAULT_GRIDWIDTH);
    setGridHeight(DEFAULT_GRIDHEIGHT);
    setWeightX(DEFAULT_WEIGHTX);
    setWeightY(DEFAULT_WEIGHTY);
    setAnchor(DEFAULT_ANCHOR);
    setFill(DEFAULT_FILL);
    setInsets(DEFAULT_INSETS);
    setInternalPadX(DEFAULT_INTERNALPADX);
    setInternalPadY(DEFAULT_INTERNALPADY);
    //--ARM-- constructor() - end
    //--ARM-- constructor() - end
  }

  protected void setPeer() {
    //--ARM-- setPeer()
    //--ARM-- setPeer()
  }

  // set/get/is methods
  //

  public Widget getWidget() {
    //--ARM-- public Widget getWidget()
    return widget;
    //--ARM-- public Widget getWidget()
  }

  public void setWidget(Widget widget) {
    //--ARM-- public void setWidget(Widget widget)
    this.widget = widget;
    //--ARM-- public void setWidget(Widget widget)
  }

  public int getGridX() {
    //--ARM-- public int getGridX()
    return gridX;
    //--ARM-- public int getGridX()
  }

  public void setGridX(int gridX) {
    //--ARM-- public void setGridX(int gridX)
    this.gridX = gridX;
    //--ARM-- public void setGridX(int gridX)
  }

  public int getGridY() {
    //--ARM-- public int getGridY()
    return gridY;
    //--ARM-- public int getGridY()
  }

  public void setGridY(int gridY) {
    //--ARM-- public void setGridY(int gridY)
    this.gridY = gridY;
    //--ARM-- public void setGridY(int gridY)
  }

  public int getGridWidth() {
    //--ARM-- public int getGridWidth()
    return gridWidth;
    //--ARM-- public int getGridWidth()
  }

  public void setGridWidth(int gridWidth) {
    //--ARM-- public void setGridWidth(int gridWidth)
    this.gridWidth = gridWidth;
    //--ARM-- public void setGridWidth(int gridWidth)
  }

  public int getGridHeight() {
    //--ARM-- public int getGridHeight()
    return gridHeight;
    //--ARM-- public int getGridHeight()
  }

  public void setGridHeight(int gridHeight) {
    //--ARM-- public void setGridHeight(int gridHeight)
    this.gridHeight = gridHeight;
    //--ARM-- public void setGridHeight(int gridHeight)
  }

  public float getWeightX() {
    //--ARM-- public float getWeightX()
    return weightX;
    //--ARM-- public float getWeightX()
  }

  public void setWeightX(float weightX) {
    //--ARM-- public void setWeightX(float weightX)
    this.weightX = weightX;
    //--ARM-- public void setWeightX(float weightX)
  }

  public float getWeightY() {
    //--ARM-- public float getWeightY()
    return weightY;
    //--ARM-- public float getWeightY()
  }

  public void setWeightY(float weightY) {
    //--ARM-- public void setWeightY(float weightY)
    this.weightY = weightY;
    //--ARM-- public void setWeightY(float weightY)
  }

  public int getAnchor() {
    //--ARM-- public int getAnchor()
    return anchor;
    //--ARM-- public int getAnchor()
  }

  public void setAnchor(int anchor) {
    //--ARM-- public void setAnchor(int anchor)
    this.anchor = anchor;
    //--ARM-- public void setAnchor(int anchor)
  }

  public int getFill() {
    //--ARM-- public int getFill()
    return fill;
    //--ARM-- public int getFill()
  }

  public void setFill(int fill) {
    //--ARM-- public void setFill(int fill)
    this.fill = fill;
    //--ARM-- public void setFill(int fill)
  }

  public Insets getInsets() {
    //--ARM-- public Insets getInsets()
    return insets;
    //--ARM-- public Insets getInsets()
  }

  public void setInsets(Insets insets) {
    //--ARM-- public void setInsets(Insets insets)
    this.insets = insets;
    //--ARM-- public void setInsets(Insets insets)
  }

  public int getInternalPadX() {
    //--ARM-- public int getInternalPadX()
    return internalPadX;
    //--ARM-- public int getInternalPadX()
  }

  public void setInternalPadX(int internalPadX) {
    //--ARM-- public void setInternalPadX(int internalPadX)
    this.internalPadX = internalPadX;
    //--ARM-- public void setInternalPadX(int internalPadX)
  }

  public int getInternalPadY() {
    //--ARM-- public int getInternalPadY()
    return internalPadY;
    //--ARM-- public int getInternalPadY()
  }

  public void setInternalPadY(int internalPadY) {
    //--ARM-- public void setInternalPadY(int internalPadY)
    this.internalPadY = internalPadY;
    //--ARM-- public void setInternalPadY(int internalPadY)
  }
}
