/*
 * Copyright (c) 2000-2002, Shayne R Flint
 * All rights reserved.
 * 
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *    * Redistributions of source code must retain the above copyright
 *      notice, this list of conditions and the following disclaimer.
 *
 *    * Redistributions in binary form must reproduce the above copyright
 *      notice, this list of conditions and the following disclaimer in the
 *      documentation and/or other materials provided with the distribution.
 *
 *    * The name of the author may not be used to endorse or promote products
 *      derived from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
 * IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
 * OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
 * IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
 * NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
 * THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/*
 * ./armidale/api/gui/impl/platform/swing/ProgressBarImpl.java
 * Generated by armidale.utilities.makeclass.Main armidale v0.9.5 on 10Apr2002 at 17:58:15
 *
 */

package armidale.api.gui.impl.platform.swing;

  import armidale.api.context.*;
  import armidale.api.gui.ProgressBar;
  import armidale.api.gui.constants.Orientation;
  import armidale.api.gui.impl.platform.swing.WidgetImpl;
  //--ARM-- imports
  import javax.swing.JProgressBar;
  //--ARM-- imports

public class ProgressBarImpl extends WidgetImpl implements ProgressBar {

  //--ARM-- declarations
  //--ARM-- declarations

  public ProgressBarImpl() {
    //--ARM-- constructor()
    //--ARM-- constructor()
    setMinimum(DEFAULT_MINIMUM);
    setMaximum(DEFAULT_MAXIMUM);
    setValue(DEFAULT_VALUE);
    setDrawProgressString(DEFAULT_DRAWPROGRESSSTRING);
    setOrientation(DEFAULT_ORIENTATION);
    //--ARM-- constructor() - end
    //--ARM-- constructor() - end
  }

  protected void setPeer() {
    //--ARM-- setPeer()
    peer = new JProgressBar();
    //--ARM-- setPeer()
  }

  // set/get/is methods
  //

  public int getMinimum() {
    //--ARM-- public int getMinimum()
    return ((JProgressBar)peer).getMinimum();
    //--ARM-- public int getMinimum()
  }

  public void setMinimum(int minimum) {
    //--ARM-- public void setMinimum(int minimum)
    ((JProgressBar)peer).setMinimum(minimum);
    //--ARM-- public void setMinimum(int minimum)
  }

  public int getMaximum() {
    //--ARM-- public int getMaximum()
    return ((JProgressBar)peer).getMaximum();
    //--ARM-- public int getMaximum()
  }

  public void setMaximum(int maximum) {
    //--ARM-- public void setMaximum(int maximum)
    ((JProgressBar)peer).setMaximum(maximum);
    //--ARM-- public void setMaximum(int maximum)
  }

  public int getValue() {
    //--ARM-- public int getValue()
    return ((JProgressBar)peer).getValue();
    //--ARM-- public int getValue()
  }

  public void setValue(int value) {
    //--ARM-- public void setValue(int value)
    ((JProgressBar)peer).setValue(value);
    //--ARM-- public void setValue(int value)
  }

  public boolean drawsProgressString() {
    //--ARM-- public boolean drawsProgressString()
    return ((JProgressBar)peer).isStringPainted();
    //--ARM-- public boolean drawsProgressString()
  }

  public void setDrawProgressString(boolean drawProgressString) {
    //--ARM-- public void setDrawProgressString(boolean drawProgressString)
    ((JProgressBar)peer).setStringPainted(drawProgressString);
    //--ARM-- public void setDrawProgressString(boolean drawProgressString)
  }

  public int getOrientation() {
    //--ARM-- public int getOrientation()
    return ((JProgressBar)peer).getOrientation();
    //--ARM-- public int getOrientation()
  }

  public void setOrientation(int orientation) {
    //--ARM-- public void setOrientation(int orientation)
    ((JProgressBar)peer).setOrientation(orientation);
    //--ARM-- public void setOrientation(int orientation)
  }
}
