/*
 * Copyright (c) 2000-2002, Shayne R Flint
 * All rights reserved.
 * 
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *    * Redistributions of source code must retain the above copyright
 *      notice, this list of conditions and the following disclaimer.
 *
 *    * Redistributions in binary form must reproduce the above copyright
 *      notice, this list of conditions and the following disclaimer in the
 *      documentation and/or other materials provided with the distribution.
 *
 *    * The name of the author may not be used to endorse or promote products
 *      derived from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
 * IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
 * OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
 * IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
 * NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
 * THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/*
 * ./armidale/api/gui/impl/platform/swing/TabbedPanelWidgetImpl.java
 * Generated by armidale.utilities.makeclass.Main armidale v0.9.5 on 10Apr2002 at 17:58:31
 *
 */

package armidale.api.gui.impl.platform.swing;

  import armidale.api.context.*;
  import armidale.api.gui.Image;
  import armidale.api.gui.TabbedPanelWidget;
  import armidale.api.gui.Widget;
  import armidale.api.impl.platform.swing.ArmidaleObjectImpl;
  //--ARM-- imports
  //--ARM-- imports

public class TabbedPanelWidgetImpl extends ArmidaleObjectImpl implements TabbedPanelWidget {

  //--ARM-- declarations
  Widget widget;
  String title;
  Image  icon;
  //--ARM-- declarations

  public TabbedPanelWidgetImpl() {
    //--ARM-- constructor()
    //--ARM-- constructor()
    setTitle(DEFAULT_TITLE);
    //--ARM-- constructor() - end
    //--ARM-- constructor() - end
  }

  protected void setPeer() {
    //--ARM-- setPeer()
    //--ARM-- setPeer()
  }

  // set/get/is methods
  //

  public Widget getWidget() {
    //--ARM-- public Widget getWidget()
    return widget;
    //--ARM-- public Widget getWidget()
  }

  public void setWidget(Widget widget) {
    //--ARM-- public void setWidget(Widget widget)
    this.widget = widget;
    //--ARM-- public void setWidget(Widget widget)
  }

  public String getTitle() {
    //--ARM-- public String getTitle()
    return title;
    //--ARM-- public String getTitle()
  }

  public void setTitle(String title) {
    //--ARM-- public void setTitle(String title)
    this.title = title;
    //--ARM-- public void setTitle(String title)
  }

  public Image getIcon() {
    //--ARM-- public Image getIcon()
    return icon;
    //--ARM-- public Image getIcon()
  }

  public void setIcon(Image icon) {
    //--ARM-- public void setIcon(Image icon)
    this.icon = icon;
    //--ARM-- public void setIcon(Image icon)
  }
}
