/*
 * Copyright (c) 2000-2002, Shayne R Flint
 * All rights reserved.
 * 
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *    * Redistributions of source code must retain the above copyright
 *      notice, this list of conditions and the following disclaimer.
 *
 *    * Redistributions in binary form must reproduce the above copyright
 *      notice, this list of conditions and the following disclaimer in the
 *      documentation and/or other materials provided with the distribution.
 *
 *    * The name of the author may not be used to endorse or promote products
 *      derived from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
 * IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
 * OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
 * IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
 * NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
 * THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/*
 * ./armidale/api/gui/impl/platform/swing/ToggleImpl.java
 * Generated by armidale.utilities.makeclass.Main armidale v0.9.5 on 10Apr2002 at 17:57:57
 *
 */

package armidale.api.gui.impl.platform.swing;

  import armidale.api.context.*;
  import armidale.api.gui.Toggle;
  import armidale.api.gui.ToggleCallback;
  import armidale.api.gui.ToggleCallbackList;
  import armidale.api.gui.impl.platform.swing.ButtonImpl;
  import java.util.LinkedList;
  //--ARM-- imports
  import javax.swing.AbstractButton;
  //--ARM-- imports

public abstract class ToggleImpl extends ButtonImpl implements Toggle {

  //--ARM-- declarations
  //--ARM-- declarations

  // Callback object
  //

  protected ToggleCallbackList toggleCallbackList = new ToggleCallbackList();

  public ToggleImpl() {
    //--ARM-- constructor()
    //--ARM-- constructor()
    setSelected(DEFAULT_SELECTED);
    //--ARM-- constructor() - end
    //--ARM-- constructor() - end
  }

  protected void setPeer() {
    //--ARM-- setPeer()
    //--ARM-- setPeer()
  }

  // Callbacks
  //

  public void addToggleCallback(ToggleCallback callback) {
    toggleCallbackList.add(callback);
    //--ARM-- public void addToggleCallback(ToggleCallback callback)
    //--ARM-- public void addToggleCallback(ToggleCallback callback)
  }

  public void removeToggleCallback(ToggleCallback callback) {
    toggleCallbackList.remove(callback);
    //--ARM-- public void removeToggleCallback(ToggleCallback callback)
    //--ARM-- public void removeToggleCallback(ToggleCallback callback)
  }

  public void removeAllToggleCallbacks() {
    toggleCallbackList.clear();
    //--ARM-- public void removeAllToggleCallbacks()
    //--ARM-- public void removeAllToggleCallbacks()
  }

  public ToggleCallbackList getToggleCallbackList() {
    //--ARM-- public ToggleCallbackList getToggleCallbackList()
    //--ARM-- public ToggleCallbackList getToggleCallbackList()
    return toggleCallbackList;
  }

  // set/get/is methods
  //

  public boolean isSelected() {
    //--ARM-- public boolean isSelected()
    return ((AbstractButton) peer).isSelected();
    //--ARM-- public boolean isSelected()
  }

  public void setSelected(boolean selected) {
    //--ARM-- public void setSelected(boolean selected)
    ((AbstractButton) peer).setSelected(selected);
    //--ARM-- public void setSelected(boolean selected)
  }
}
