/*
 * Copyright (c) 2000-2002, Shayne R Flint
 * All rights reserved.
 * 
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *    * Redistributions of source code must retain the above copyright
 *      notice, this list of conditions and the following disclaimer.
 *
 *    * Redistributions in binary form must reproduce the above copyright
 *      notice, this list of conditions and the following disclaimer in the
 *      documentation and/or other materials provided with the distribution.
 *
 *    * The name of the author may not be used to endorse or promote products
 *      derived from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
 * IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
 * OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
 * IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
 * NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
 * THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/*
 * ./armidale/api/gui/impl/platform/swing/WidgetImpl.java
 * Generated by armidale.utilities.makeclass.Main armidale v0.9.5 on 10Apr2002 at 17:57:48
 *
 */

package armidale.api.gui.impl.platform.swing;

  import armidale.api.context.*;
  import armidale.api.gui.Size;
  import armidale.api.gui.Widget;
  import armidale.api.gui.impl.platform.swing.ComponentImpl;
  //--ARM-- imports
import javax.swing.JComponent;
  //--ARM-- imports

public abstract class WidgetImpl extends ComponentImpl implements Widget {

  //--ARM-- declarations
  //--ARM-- declarations

  public WidgetImpl() {
    //--ARM-- constructor()
    //--ARM-- constructor()
    setAlignmentX(DEFAULT_ALIGNMENTX);
    setAlignmentY(DEFAULT_ALIGNMENTY);
    //--ARM-- constructor() - end
    //--ARM-- constructor() - end
  }

  protected void setPeer() {
    //--ARM-- setPeer()
    //--ARM-- setPeer()
  }

  // set/get/is methods
  //
  public void setPreferredSize(Size preferredSize) {
    //--ARM-- public void setPreferredSize(Size preferredSize)
    ((JComponent) peer).setPreferredSize(Conversions.awtDimension(preferredSize));
    //--ARM-- public void setPreferredSize(Size preferredSize)
  }
  public void setMinimumSize(Size minimumSize) {
    //--ARM-- public void setMinimumSize(Size minimumSize)
    ((JComponent) peer).setMinimumSize(Conversions.awtDimension(minimumSize));
    //--ARM-- public void setMinimumSize(Size minimumSize)
  }
  public void setMaximumSize(Size maximumSize) {
    //--ARM-- public void setMaximumSize(Size maximumSize)
    ((JComponent) peer).setMaximumSize(Conversions.awtDimension(maximumSize));
    //--ARM-- public void setMaximumSize(Size maximumSize)
  }

  public float getAlignmentX() {
    //--ARM-- public float getAlignmentX()
    return ((JComponent) peer).getAlignmentX();
    //--ARM-- public float getAlignmentX()
  }

  public void setAlignmentX(float alignmentX) {
    //--ARM-- public void setAlignmentX(float alignmentX)
    ((JComponent) peer).setAlignmentX(alignmentX);
    //--ARM-- public void setAlignmentX(float alignmentX)
  }

  public float getAlignmentY() {
    //--ARM-- public float getAlignmentY()
    return ((JComponent) peer).getAlignmentY();
    //--ARM-- public float getAlignmentY()
  }

  public void setAlignmentY(float alignmentY) {
    //--ARM-- public void setAlignmentY(float alignmentY)
    ((JComponent) peer).setAlignmentY(alignmentY);
    //--ARM-- public void setAlignmentY(float alignmentY)
  }

  // other methods
  //

  public void setSize(Size size) {
    //--ARM-- public void setSize(Size size)
    setPreferredSize(size);
    setMinimumSize(size);
    setMaximumSize(size);
    //--ARM-- public void setSize(Size size)
  }

}
