/*
 * Copyright (c) 2000-2002, Shayne R Flint
 * All rights reserved.
 * 
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *    * Redistributions of source code must retain the above copyright
 *      notice, this list of conditions and the following disclaimer.
 *
 *    * Redistributions in binary form must reproduce the above copyright
 *      notice, this list of conditions and the following disclaimer in the
 *      documentation and/or other materials provided with the distribution.
 *
 *    * The name of the author may not be used to endorse or promote products
 *      derived from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
 * IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
 * OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
 * IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
 * NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
 * THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/*
 * ./armidale/api/gui/impl/platform/swing/WindowImpl.java
 * Generated by armidale.utilities.makeclass.Main armidale v0.9.5 on 10Apr2002 at 17:58:25
 *
 */

package armidale.api.gui.impl.platform.swing;

  import armidale.api.context.*;
  import armidale.api.gui.Window;
  import armidale.api.gui.WindowCallback;
  import armidale.api.gui.WindowCallbackList;
  import armidale.api.gui.impl.platform.swing.VisibleObjectImpl;
  import java.util.LinkedList;
  //--ARM-- imports
  //--ARM-- imports

public abstract class WindowImpl extends VisibleObjectImpl implements Window {

  //--ARM-- declarations
  private class SwingComponentListener extends java.awt.event.ComponentAdapter {
    
    public void componentMoved(java.awt.event.ComponentEvent e) {
      windowCallbackList.windowMoved(WindowImpl.this, Conversions.position(((java.awt.Component)peer).getLocation()));
    }

    public void componentResized(java.awt.event.ComponentEvent e) {
      windowCallbackList.windowResized(WindowImpl.this, Conversions.size(((java.awt.Component)peer).getSize()));
    }
  }
  //--ARM-- declarations

  // Callback object
  //

  protected WindowCallbackList windowCallbackList = new WindowCallbackList();

  public WindowImpl() {
    //--ARM-- constructor()
    //--ARM-- constructor()
    //--ARM-- constructor() - end
    ((java.awt.Component)peer).addComponentListener(new SwingComponentListener());
    //--ARM-- constructor() - end
  }

  protected void setPeer() {
    //--ARM-- setPeer()
    //--ARM-- setPeer()
  }

  // Callbacks
  //

  public void addWindowCallback(WindowCallback callback) {
    windowCallbackList.add(callback);
    //--ARM-- public void addWindowCallback(WindowCallback callback)
    //--ARM-- public void addWindowCallback(WindowCallback callback)
  }

  public void removeWindowCallback(WindowCallback callback) {
    windowCallbackList.remove(callback);
    //--ARM-- public void removeWindowCallback(WindowCallback callback)
    //--ARM-- public void removeWindowCallback(WindowCallback callback)
  }

  public void removeAllWindowCallbacks() {
    windowCallbackList.clear();
    //--ARM-- public void removeAllWindowCallbacks()
    //--ARM-- public void removeAllWindowCallbacks()
  }

  public WindowCallbackList getWindowCallbackList() {
    //--ARM-- public WindowCallbackList getWindowCallbackList()
    //--ARM-- public WindowCallbackList getWindowCallbackList()
    return windowCallbackList;
  }

  // other methods
  //

  public void dispose() {
    //--ARM-- public void dispose()
    //--ARM-- public void dispose()
  }

}
