/*
 * Copyright (c) 2000-2002, Shayne R Flint
 * All rights reserved.
 * 
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *    * Redistributions of source code must retain the above copyright
 *      notice, this list of conditions and the following disclaimer.
 *
 *    * Redistributions in binary form must reproduce the above copyright
 *      notice, this list of conditions and the following disclaimer in the
 *      documentation and/or other materials provided with the distribution.
 *
 *    * The name of the author may not be used to endorse or promote products
 *      derived from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
 * IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
 * OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
 * IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
 * NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
 * THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/*
 * ./armidale/api/gui/Component.java
 * Generated by armidale.utilities.makeclass.Main armidale v0.9.5 on 10Apr2002 at 17:57:44
 *
 */

package armidale.api.gui;
  /**
   *
   * @author  generated by <tt>armidale.utilities.makeclass.Main</tt> on 10Apr2002 at 17:57:44
   * @version armidale v0.9.5
   */

  import armidale.api.gui.constants.CursorType;

public interface Component extends VisibleObject, CursorType {

  // Attributes Defaults
  //
  public static final boolean DEFAULT_ENABLED = true;
  public static final String DEFAULT_TOOLTIP = "";
  public static final Font DEFAULT_FONT = new Font(Font.DIALOG, 12, true, false);
  public static final Color DEFAULT_FOREGROUNDCOLOR = Color.BLACK;
  public static final Color DEFAULT_BACKGROUNDCOLOR = new Color(204, 204, 204);
  public static final int DEFAULT_CURSORTYPE = DEFAULT_CURSOR;
  public static final boolean DEFAULT_COMPONENT_VISIBLE = true;

  // attribute set/get/is methods
  //

  /**
   * Returns the value of the <tt>enabled</tt> attribute.
   * <p>
   *
   * @return value of the <tt>enabled</tt> attribute
   */
  public boolean isEnabled();

  /**
   * Sets the <tt>enabled</tt> attribute.
   * <p>
   *
   * @param  enabled value of the <tt>enabled</tt> attribute. 
   */
  public void setEnabled(boolean enabled);

  /**
   * Returns the value of the <tt>toolTip</tt> attribute.
   * <p>
   *
   * @return value of the <tt>toolTip</tt> attribute
   */
  public String getToolTip();

  /**
   * Sets the <tt>toolTip</tt> attribute.
   * <p>
   *
   * @param  toolTip value of the <tt>toolTip</tt> attribute. 
   */
  public void setToolTip(String toolTip);

  /**
   * Returns the value of the <tt>popupMenu</tt> attribute.
   * <p>
   *
   * @return value of the <tt>popupMenu</tt> attribute
   */
  public PopupMenu getPopupMenu();

  /**
   * Sets the <tt>popupMenu</tt> attribute.
   * <p>
   *
   * @param  popupMenu value of the <tt>popupMenu</tt> attribute. 
   */
  public void setPopupMenu(PopupMenu popupMenu);

  /**
   * Returns the value of the <tt>font</tt> attribute.
   * <p>
   *
   * @return value of the <tt>font</tt> attribute
   */
  public Font getFont();

  /**
   * Sets the <tt>font</tt> attribute.
   * <p>
   *
   * @param  font value of the <tt>font</tt> attribute. 
   */
  public void setFont(Font font);

  /**
   * Returns the value of the <tt>foregroundColor</tt> attribute.
   * <p>
   *
   * @return value of the <tt>foregroundColor</tt> attribute
   */
  public Color getForegroundColor();

  /**
   * Sets the <tt>foregroundColor</tt> attribute.
   * <p>
   *
   * @param  foregroundColor value of the <tt>foregroundColor</tt> attribute. 
   */
  public void setForegroundColor(Color foregroundColor);

  /**
   * Returns the value of the <tt>backgroundColor</tt> attribute.
   * <p>
   *
   * @return value of the <tt>backgroundColor</tt> attribute
   */
  public Color getBackgroundColor();

  /**
   * Sets the <tt>backgroundColor</tt> attribute.
   * <p>
   *
   * @param  backgroundColor value of the <tt>backgroundColor</tt> attribute. 
   */
  public void setBackgroundColor(Color backgroundColor);

  /**
   * Returns the value of the <tt>cursorType</tt> attribute.
   * <p>
   *
   * @return value of the <tt>cursorType</tt> attribute
   */
  public int getCursorType();

  /**
   * Sets the <tt>cursorType</tt> attribute.
   * <p>
   *
   * @param  cursorType value of the <tt>cursorType</tt> attribute. 
   * Values for this parameter are defined in the {@link armidale.api.gui.constants.CursorType armidale.api.gui.constants.CursorType} interface
   */
  public void setCursorType(int cursorType);
}
