/*
 * Copyright (c) 2000-2002, Shayne R Flint
 * All rights reserved.
 * 
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *    * Redistributions of source code must retain the above copyright
 *      notice, this list of conditions and the following disclaimer.
 *
 *    * Redistributions in binary form must reproduce the above copyright
 *      notice, this list of conditions and the following disclaimer in the
 *      documentation and/or other materials provided with the distribution.
 *
 *    * The name of the author may not be used to endorse or promote products
 *      derived from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
 * IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
 * OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
 * IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
 * NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
 * THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/*
 * ./armidale/api/gui/Desktop.java
 * Generated by armidale.utilities.makeclass.Main armidale v0.9.5 on 10Apr2002 at 17:58:02
 *
 */

package armidale.api.gui;
  /**
   *
   * @author  generated by <tt>armidale.utilities.makeclass.Main</tt> on 10Apr2002 at 17:58:02
   * @version armidale v0.9.5
   */

  import armidale.api.gui.constants.WallpaperModes;

public interface Desktop extends Widget, WallpaperModes {

  // Attributes Defaults
  //
  public static final int DEFAULT_WALLPAPERMODE = TILED;

  // attribute set/get/is methods
  //

  /**
   * Returns the value of the <tt>wallpaper</tt> attribute.
   * <p>
   *
   * @return value of the <tt>wallpaper</tt> attribute
   */
  public Image getWallpaper();

  /**
   * Sets the <tt>wallpaper</tt> attribute.
   * <p>
   *
   * @param  wallpaper value of the <tt>wallpaper</tt> attribute. 
   */
  public void setWallpaper(Image wallpaper);

  /**
   * Returns the value of the <tt>wallpaperMode</tt> attribute.
   * <p>
   *
   * @return value of the <tt>wallpaperMode</tt> attribute
   */
  public int getWallpaperMode();

  /**
   * Sets the <tt>wallpaperMode</tt> attribute.
   * <p>
   *
   * @param  wallpaperMode value of the <tt>wallpaperMode</tt> attribute. 
   * Values for this parameter are defined in the {@link armidale.api.gui.constants.WallpaperModes armidale.api.gui.constants.WallpaperModes} interface
   */
  public void setWallpaperMode(int wallpaperMode);

  // other methods
  //

  /**
   * Adds a specified InternalFrame to the list of InternalFrames associated 
   * with this Desktop.
   * <p>
   * @see #addInternalFrame
   * @see #removeInternalFrame
   * @see #removeAllInternalFrames
   *
   * @param internalFrame InternalFrame to be added
   */
  public void addInternalFrame(InternalFrame internalFrame);

  /**
   * Removes a specified InternalFrame from the list of InternalFrames 
   * associated with this Desktop.
   * <p>
   * @see #addInternalFrame
   * @see #removeInternalFrame
   * @see #removeAllInternalFrames
   *
   * @param internalFrame InternalFrame to be removed
   */
  public void removeInternalFrame(InternalFrame internalFrame);

  /**
   * Clears the list of InternalFrames associated with this Desktop.
   * <p>
   * @see #addInternalFrame
   * @see #removeInternalFrame
   * @see #removeAllInternalFrames
   *
   */
  public void removeAllInternalFrames();
}
