/*
 * Copyright (c) 2000-2002, Shayne R Flint
 * All rights reserved.
 * 
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *    * Redistributions of source code must retain the above copyright
 *      notice, this list of conditions and the following disclaimer.
 *
 *    * Redistributions in binary form must reproduce the above copyright
 *      notice, this list of conditions and the following disclaimer in the
 *      documentation and/or other materials provided with the distribution.
 *
 *    * The name of the author may not be used to endorse or promote products
 *      derived from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
 * IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
 * OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
 * IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
 * NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
 * THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/*
 * ./armidale/api/gui/Frame.java
 * Generated by armidale.utilities.makeclass.Main armidale v0.9.5 on 10Apr2002 at 17:58:26
 *
 */

package armidale.api.gui;
  /**
   * <p>All gui widgets that interact with the user are derived ultimately from 
   * the <tt>ActionWidget</tt> interface.</p> <p>This is a some more junk for 
   * test purposes.</p>
   * <p>
   *
   * @author  generated by <tt>armidale.utilities.makeclass.Main</tt> on 10Apr2002 at 17:58:26
   * @version armidale v0.9.5
   */

  import armidale.api.gui.constants.Compass;

public interface Frame extends Window, Compass {

  // Attributes Defaults
  //
  public static final Size DEFAULT_SIZE = new Size(300, 200);
  public static final Position DEFAULT_POSITION = new Position(0,0);
  public static final boolean DEFAULT_RESIZABLE = true;
  public static final String DEFAULT_TITLE = "armidale";
  public static final Color DEFAULT_BACKGROUNDCOLOR = new Color(204, 204, 204);

  // attribute set/get/is methods
  //

  /**
   * Returns the value of the <tt>size</tt> attribute.
   * <p>
   * <p>attribute <tt>size</tt> documentation h frhiurh fiue hfiuer fui eriuf 
   * heriuf iuerfh ui fuie ruifhre uif eriufh reiu fiuer hfiu eruif</p>
   * <p>
   *
   * @return value of the <tt>size</tt> attribute
   */
  public Size getSize();

  /**
   * Sets the <tt>size</tt> attribute.
   * <p>
   * <p>attribute <tt>size</tt> documentation h frhiurh fiue hfiuer fui eriuf 
   * heriuf iuerfh ui fuie ruifhre uif eriufh reiu fiuer hfiu eruif</p>
   * <p>
   *
   * @param  size value of the <tt>size</tt> attribute. 
   */
  public void setSize(Size size);

  /**
   * Returns the value of the <tt>position</tt> attribute.
   * <p>
   *
   * @return value of the <tt>position</tt> attribute
   */
  public Position getPosition();

  /**
   * Sets the <tt>position</tt> attribute.
   * <p>
   *
   * @param  position value of the <tt>position</tt> attribute. 
   */
  public void setPosition(Position position);

  /**
   * Returns the value of the <tt>resizable</tt> attribute.
   * <p>
   *
   * @return value of the <tt>resizable</tt> attribute
   */
  public boolean isResizable();

  /**
   * Sets the <tt>resizable</tt> attribute.
   * <p>
   *
   * @param  resizable value of the <tt>resizable</tt> attribute. 
   */
  public void setResizable(boolean resizable);

  /**
   * Returns the value of the <tt>title</tt> attribute.
   * <p>
   *
   * @return value of the <tt>title</tt> attribute
   */
  public String getTitle();

  /**
   * Sets the <tt>title</tt> attribute.
   * <p>
   *
   * @param  title value of the <tt>title</tt> attribute. 
   */
  public void setTitle(String title);

  /**
   * Returns the value of the <tt>content</tt> attribute.
   * <p>
   *
   * @return value of the <tt>content</tt> attribute
   */
  public Widget getContent();

  /**
   * Sets the <tt>content</tt> attribute.
   * <p>
   *
   * @param  content value of the <tt>content</tt> attribute. 
   */
  public void setContent(Widget content);

  /**
   * Returns the value of the <tt>icon</tt> attribute.
   * <p>
   *
   * @return value of the <tt>icon</tt> attribute
   */
  public Image getIcon();

  /**
   * Sets the <tt>icon</tt> attribute.
   * <p>
   *
   * @param  icon value of the <tt>icon</tt> attribute. 
   */
  public void setIcon(Image icon);

  /**
   * Returns the value of the <tt>menubar</tt> attribute.
   * <p>
   *
   * @return value of the <tt>menubar</tt> attribute
   */
  public MenuBar getMenubar();

  /**
   * Sets the <tt>menubar</tt> attribute.
   * <p>
   *
   * @param  menubar value of the <tt>menubar</tt> attribute. 
   */
  public void setMenubar(MenuBar menubar);

  /**
   * Returns the value of the <tt>toolbar</tt> attribute.
   * <p>
   *
   * @return value of the <tt>toolbar</tt> attribute
   */
  public Widget getToolbar();

  /**
   * Sets the <tt>toolbar</tt> attribute.
   * <p>
   *
   * @param  toolbar value of the <tt>toolbar</tt> attribute. 
   */
  public void setToolbar(Widget toolbar);

  /**
   * Returns the value of the <tt>statusbar</tt> attribute.
   * <p>
   *
   * @return value of the <tt>statusbar</tt> attribute
   */
  public Widget getStatusbar();

  /**
   * Sets the <tt>statusbar</tt> attribute.
   * <p>
   *
   * @param  statusbar value of the <tt>statusbar</tt> attribute. 
   */
  public void setStatusbar(Widget statusbar);

  /**
   * Returns the value of the <tt>backgroundColor</tt> attribute.
   * <p>
   *
   * @return value of the <tt>backgroundColor</tt> attribute
   */
  public Color getBackgroundColor();

  /**
   * Sets the <tt>backgroundColor</tt> attribute.
   * <p>
   *
   * @param  backgroundColor value of the <tt>backgroundColor</tt> attribute. 
   */
  public void setBackgroundColor(Color backgroundColor);

  // other methods
  //

  /**
   * <p>Method documentation</p>
   * <p>
   *
   * @param xAlign parameter documentation h frhiurh fiue hfiuer fui eriuf 
   * heriuf iuerfh ui fuie ruifhre uif eriufh reiu fiuer hfiu eruif
   * <p>
   * @param yAlign parameter documentation
   * <p>
   */
  public void setAlignment(float xAlign, float yAlign);

  /**
   *
   * @param alignment
   * Values for this parameter are defined in the {@link armidale.api.gui.constants.Compass armidale.api.gui.constants.Compass} interface
   */
  public void setAlignment(int alignment);
}
