/*
 * Copyright (c) 2000-2002, Shayne R Flint
 * All rights reserved.
 * 
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *    * Redistributions of source code must retain the above copyright
 *      notice, this list of conditions and the following disclaimer.
 *
 *    * Redistributions in binary form must reproduce the above copyright
 *      notice, this list of conditions and the following disclaimer in the
 *      documentation and/or other materials provided with the distribution.
 *
 *    * The name of the author may not be used to endorse or promote products
 *      derived from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
 * IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
 * OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
 * IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
 * NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
 * THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/*
 * ./armidale/api/gui/Image.java
 * Generated by armidale.utilities.makeclass.Main armidale v0.9.5 on 10Apr2002 at 17:57:42
 *
 */

package armidale.api.gui;
  /**
   *
   * @author  generated by <tt>armidale.utilities.makeclass.Main</tt> on 10Apr2002 at 17:57:42
   * @version armidale v0.9.5
   */

  import armidale.api.ArmidaleObject;
  import armidale.api.io.File;
  import armidale.api.structures.ByteArray;

public interface Image extends ArmidaleObject {

  // Attributes Defaults
  //
  public static final String DEFAULT_DESCRIPTION = "<image>";

  // attribute set/get/is methods
  //

  /**
   * Sets the <tt>imageData</tt> attribute.
   * <p>
   *
   * @param  imageData value of the <tt>imageData</tt> attribute. 
   */
  public void setImageData(ByteArray imageData);

  /**
   * Returns the value of the <tt>size</tt> attribute.
   * <p>
   *
   * @return value of the <tt>size</tt> attribute
   */
  public Size getSize();

  /**
   * Sets the <tt>size</tt> attribute.
   * <p>
   *
   * @param  size value of the <tt>size</tt> attribute. 
   */
  public void setSize(Size size);

  /**
   * Sets the <tt>file</tt> attribute.
   * <p>
   *
   * @param  file value of the <tt>file</tt> attribute. 
   */
  public void setFile(File file);

  /**
   * Returns the value of the <tt>description</tt> attribute.
   * <p>
   *
   * @return value of the <tt>description</tt> attribute
   */
  public String getDescription();

  /**
   * Sets the <tt>description</tt> attribute.
   * <p>
   *
   * @param  description value of the <tt>description</tt> attribute. 
   */
  public void setDescription(String description);

  // callback
  //

  /**
   * Registers a callback with this Image
   *
   * @param  callback callback to be added
   *
   */
  public void addImageCallback(ImageCallback callback);

  /**
   * Removes a callback registered with this Image
   *
   * @param  callback callback to be removed
   */
  public void removeImageCallback(ImageCallback callback);

  /**
   * Removes all callbacks registered with this Image
   *
   */
  public void removeAllImageCallbacks();

  /**
   * Returns the list of callbacks registered with this Image
   *
   * @return list of callbacks registered with this object
   */
  public ImageCallbackList getImageCallbackList();
}
