/*
 * Copyright (c) 2000-2002, Shayne R Flint
 * All rights reserved.
 * 
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *    * Redistributions of source code must retain the above copyright
 *      notice, this list of conditions and the following disclaimer.
 *
 *    * Redistributions in binary form must reproduce the above copyright
 *      notice, this list of conditions and the following disclaimer in the
 *      documentation and/or other materials provided with the distribution.
 *
 *    * The name of the author may not be used to endorse or promote products
 *      derived from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
 * IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
 * OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
 * IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
 * NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
 * THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/*
 * ./armidale/api/gui/LabeledWidget.java
 * Generated by armidale.utilities.makeclass.Main armidale v0.9.5 on 10Apr2002 at 17:58:03
 *
 */

package armidale.api.gui;
  /**
   *
   * @author  generated by <tt>armidale.utilities.makeclass.Main</tt> on 10Apr2002 at 17:58:03
   * @version armidale v0.9.5
   */

  import armidale.api.gui.constants.Compass;

public interface LabeledWidget extends Panel, Compass {

  // Attributes Defaults
  //
  public static final String DEFAULT_TEXT = "";
  public static final int DEFAULT_TEXTIMAGEALIGNMENT = EAST;
  public static final int DEFAULT_TEXTIMAGEGAP = 4;
  public static final int DEFAULT_LABELWIDGETALIGNMENT = NORTH_WEST;
  public static final int DEFAULT_LABELWIDGETGAP = 4;

  // attribute set/get/is methods
  //

  /**
   * Returns the value of the <tt>image</tt> attribute.
   * <p>
   *
   * @return value of the <tt>image</tt> attribute
   */
  public Image getImage();

  /**
   * Sets the <tt>image</tt> attribute.
   * <p>
   *
   * @param  image value of the <tt>image</tt> attribute. 
   */
  public void setImage(Image image);

  /**
   * Returns the value of the <tt>text</tt> attribute.
   * <p>
   *
   * @return value of the <tt>text</tt> attribute
   */
  public String getText();

  /**
   * Sets the <tt>text</tt> attribute.
   * <p>
   *
   * @param  text value of the <tt>text</tt> attribute. 
   */
  public void setText(String text);

  /**
   * Returns the value of the <tt>widget</tt> attribute.
   * <p>
   *
   * @return value of the <tt>widget</tt> attribute
   */
  public Widget getWidget();

  /**
   * Sets the <tt>widget</tt> attribute.
   * <p>
   *
   * @param  widget value of the <tt>widget</tt> attribute. 
   */
  public void setWidget(Widget widget);

  /**
   * Returns the value of the <tt>textImageAlignment</tt> attribute.
   * <p>
   *
   * @return value of the <tt>textImageAlignment</tt> attribute
   */
  public int getTextImageAlignment();

  /**
   * Sets the <tt>textImageAlignment</tt> attribute.
   * <p>
   *
   * @param  textImageAlignment value of the <tt>textImageAlignment</tt> attribute. 
   * Values for this parameter are defined in the {@link armidale.api.gui.constants.Compass armidale.api.gui.constants.Compass} interface
   */
  public void setTextImageAlignment(int textImageAlignment);

  /**
   * Returns the value of the <tt>textImageGap</tt> attribute.
   * <p>
   *
   * @return value of the <tt>textImageGap</tt> attribute
   */
  public int getTextImageGap();

  /**
   * Sets the <tt>textImageGap</tt> attribute.
   * <p>
   *
   * @param  textImageGap value of the <tt>textImageGap</tt> attribute. 
   */
  public void setTextImageGap(int textImageGap);

  /**
   * Returns the value of the <tt>labelWidgetAlignment</tt> attribute.
   * <p>
   *
   * @return value of the <tt>labelWidgetAlignment</tt> attribute
   */
  public int getLabelWidgetAlignment();

  /**
   * Sets the <tt>labelWidgetAlignment</tt> attribute.
   * <p>
   *
   * @param  labelWidgetAlignment value of the <tt>labelWidgetAlignment</tt> attribute. 
   * Values for this parameter are defined in the {@link armidale.api.gui.constants.Compass armidale.api.gui.constants.Compass} interface
   */
  public void setLabelWidgetAlignment(int labelWidgetAlignment);

  /**
   * Returns the value of the <tt>labelWidgetGap</tt> attribute.
   * <p>
   *
   * @return value of the <tt>labelWidgetGap</tt> attribute
   */
  public int getLabelWidgetGap();

  /**
   * Sets the <tt>labelWidgetGap</tt> attribute.
   * <p>
   *
   * @param  labelWidgetGap value of the <tt>labelWidgetGap</tt> attribute. 
   */
  public void setLabelWidgetGap(int labelWidgetGap);
}
