/*
 * Copyright (c) 2000-2002, Shayne R Flint
 * All rights reserved.
 * 
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *    * Redistributions of source code must retain the above copyright
 *      notice, this list of conditions and the following disclaimer.
 *
 *    * Redistributions in binary form must reproduce the above copyright
 *      notice, this list of conditions and the following disclaimer in the
 *      documentation and/or other materials provided with the distribution.
 *
 *    * The name of the author may not be used to endorse or promote products
 *      derived from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
 * IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
 * OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
 * IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
 * NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
 * THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/*
 * ./armidale/api/gui/Panel.java
 * Generated by armidale.utilities.makeclass.Main armidale v0.9.5 on 10Apr2002 at 17:58:06
 *
 */

package armidale.api.gui;
  /**
   *
   * @author  generated by <tt>armidale.utilities.makeclass.Main</tt> on 10Apr2002 at 17:58:06
   * @version armidale v0.9.5
   */

  import armidale.api.gui.constants.EdgeStyle;

public interface Panel extends Widget, EdgeStyle {

  // Attributes Defaults
  //
  public static final String DEFAULT_TITLE = "";
  public static final int DEFAULT_EDGESTYLE = NONE;
  public static final Color DEFAULT_EDGECOLOR = new Color(204, 204, 204);

  // attribute set/get/is methods
  //

  /**
   * Returns the value of the <tt>title</tt> attribute.
   * <p>
   *
   * @return value of the <tt>title</tt> attribute
   */
  public String getTitle();

  /**
   * Sets the <tt>title</tt> attribute.
   * <p>
   *
   * @param  title value of the <tt>title</tt> attribute. 
   */
  public void setTitle(String title);

  /**
   * Returns the value of the <tt>edgeStyle</tt> attribute.
   * <p>
   *
   * @return value of the <tt>edgeStyle</tt> attribute
   */
  public int getEdgeStyle();

  /**
   * Sets the <tt>edgeStyle</tt> attribute.
   * <p>
   *
   * @param  edgeStyle value of the <tt>edgeStyle</tt> attribute. 
   * Values for this parameter are defined in the {@link armidale.api.gui.constants.EdgeStyle armidale.api.gui.constants.EdgeStyle} interface
   */
  public void setEdgeStyle(int edgeStyle);

  /**
   * Returns the value of the <tt>edgeColor</tt> attribute.
   * <p>
   *
   * @return value of the <tt>edgeColor</tt> attribute
   */
  public Color getEdgeColor();

  /**
   * Sets the <tt>edgeColor</tt> attribute.
   * <p>
   *
   * @param  edgeColor value of the <tt>edgeColor</tt> attribute. 
   */
  public void setEdgeColor(Color edgeColor);
}
