/*
 * Copyright (c) 2000-2002, Shayne R Flint
 * All rights reserved.
 * 
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *    * Redistributions of source code must retain the above copyright
 *      notice, this list of conditions and the following disclaimer.
 *
 *    * Redistributions in binary form must reproduce the above copyright
 *      notice, this list of conditions and the following disclaimer in the
 *      documentation and/or other materials provided with the distribution.
 *
 *    * The name of the author may not be used to endorse or promote products
 *      derived from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
 * IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
 * OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
 * IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
 * NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
 * THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/*
 * ./armidale/api/gui/ProgressBar.java
 * Generated by armidale.utilities.makeclass.Main armidale v0.9.5 on 10Apr2002 at 17:58:15
 *
 */

package armidale.api.gui;
  /**
   *
   * @author  generated by <tt>armidale.utilities.makeclass.Main</tt> on 10Apr2002 at 17:58:15
   * @version armidale v0.9.5
   */

  import armidale.api.gui.constants.Orientation;

public interface ProgressBar extends Widget, Orientation {

  // Attributes Defaults
  //
  public static final int DEFAULT_MINIMUM = 0;
  public static final int DEFAULT_MAXIMUM = 100;
  public static final int DEFAULT_VALUE = 0;
  public static final boolean DEFAULT_DRAWPROGRESSSTRING = true;
  public static final int DEFAULT_ORIENTATION = HORIZONTAL;

  // attribute set/get/is methods
  //

  /**
   * Returns the value of the <tt>minimum</tt> attribute.
   * <p>
   *
   * @return value of the <tt>minimum</tt> attribute
   */
  public int getMinimum();

  /**
   * Sets the <tt>minimum</tt> attribute.
   * <p>
   *
   * @param  minimum value of the <tt>minimum</tt> attribute. 
   */
  public void setMinimum(int minimum);

  /**
   * Returns the value of the <tt>maximum</tt> attribute.
   * <p>
   *
   * @return value of the <tt>maximum</tt> attribute
   */
  public int getMaximum();

  /**
   * Sets the <tt>maximum</tt> attribute.
   * <p>
   *
   * @param  maximum value of the <tt>maximum</tt> attribute. 
   */
  public void setMaximum(int maximum);

  /**
   * Returns the value of the <tt>value</tt> attribute.
   * <p>
   *
   * @return value of the <tt>value</tt> attribute
   */
  public int getValue();

  /**
   * Sets the <tt>value</tt> attribute.
   * <p>
   *
   * @param  value value of the <tt>value</tt> attribute. 
   */
  public void setValue(int value);

  /**
   * Returns the value of the <tt>drawProgressString</tt> attribute.
   * <p>
   *
   * @return value of the <tt>drawProgressString</tt> attribute
   */
  public boolean drawsProgressString();

  /**
   * Sets the <tt>drawProgressString</tt> attribute.
   * <p>
   *
   * @param  drawProgressString value of the <tt>drawProgressString</tt> attribute. 
   */
  public void setDrawProgressString(boolean drawProgressString);

  /**
   * Returns the value of the <tt>orientation</tt> attribute.
   * <p>
   *
   * @return value of the <tt>orientation</tt> attribute
   */
  public int getOrientation();

  /**
   * Sets the <tt>orientation</tt> attribute.
   * <p>
   *
   * @param  orientation value of the <tt>orientation</tt> attribute. 
   * Values for this parameter are defined in the {@link armidale.api.gui.constants.Orientation armidale.api.gui.constants.Orientation} interface
   */
  public void setOrientation(int orientation);
}
