/*
 * Copyright (c) 2000-2002, Shayne R Flint
 * All rights reserved.
 * 
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *    * Redistributions of source code must retain the above copyright
 *      notice, this list of conditions and the following disclaimer.
 *
 *    * Redistributions in binary form must reproduce the above copyright
 *      notice, this list of conditions and the following disclaimer in the
 *      documentation and/or other materials provided with the distribution.
 *
 *    * The name of the author may not be used to endorse or promote products
 *      derived from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
 * IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
 * OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
 * IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
 * NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
 * THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/*
 * ./armidale/api/gui/SplitPanel.java
 * Generated by armidale.utilities.makeclass.Main armidale v0.9.5 on 10Apr2002 at 17:58:18
 *
 */

package armidale.api.gui;
  /**
   *
   * @author  generated by <tt>armidale.utilities.makeclass.Main</tt> on 10Apr2002 at 17:58:18
   * @version armidale v0.9.5
   */

  import armidale.api.gui.constants.Orientation;

public interface SplitPanel extends Widget, Orientation {

  // Attributes Defaults
  //
  public static final int DEFAULT_ORIENTATION = HORIZONTAL;
  public static final float DEFAULT_DIVIDERLOCATION = 0.5f;
  public static final int DEFAULT_DIVIDERSIZE = 10;
  public static final float DEFAULT_RESIZEWEIGHT = 0.5f;
  public static final boolean DEFAULT_EXPANDABLE = false;

  // attribute set/get/is methods
  //

  /**
   * Returns the value of the <tt>orientation</tt> attribute.
   * <p>
   *
   * @return value of the <tt>orientation</tt> attribute
   */
  public int getOrientation();

  /**
   * Sets the <tt>orientation</tt> attribute.
   * <p>
   *
   * @param  orientation value of the <tt>orientation</tt> attribute. 
   * Values for this parameter are defined in the {@link armidale.api.gui.constants.Orientation armidale.api.gui.constants.Orientation} interface
   */
  public void setOrientation(int orientation);

  /**
   * Returns the value of the <tt>dividerLocation</tt> attribute.
   * <p>
   *
   * @return value of the <tt>dividerLocation</tt> attribute
   */
  public float getDividerLocation();

  /**
   * Sets the <tt>dividerLocation</tt> attribute.
   * <p>
   *
   * @param  dividerLocation value of the <tt>dividerLocation</tt> attribute. 
   */
  public void setDividerLocation(float dividerLocation);

  /**
   * Returns the value of the <tt>dividerSize</tt> attribute.
   * <p>
   *
   * @return value of the <tt>dividerSize</tt> attribute
   */
  public int getDividerSize();

  /**
   * Sets the <tt>dividerSize</tt> attribute.
   * <p>
   *
   * @param  dividerSize value of the <tt>dividerSize</tt> attribute. 
   */
  public void setDividerSize(int dividerSize);

  /**
   * Returns the value of the <tt>resizeWeight</tt> attribute.
   * <p>
   *
   * @return value of the <tt>resizeWeight</tt> attribute
   */
  public float getResizeWeight();

  /**
   * Sets the <tt>resizeWeight</tt> attribute.
   * <p>
   *
   * @param  resizeWeight value of the <tt>resizeWeight</tt> attribute. 
   */
  public void setResizeWeight(float resizeWeight);

  /**
   * Returns the value of the <tt>expandable</tt> attribute.
   * <p>
   *
   * @return value of the <tt>expandable</tt> attribute
   */
  public boolean isExpandable();

  /**
   * Sets the <tt>expandable</tt> attribute.
   * <p>
   *
   * @param  expandable value of the <tt>expandable</tt> attribute. 
   */
  public void setExpandable(boolean expandable);

  /**
   * Returns the value of the <tt>leftWidget</tt> attribute.
   * <p>
   * the widget located to the left or above the divider
   * <p>
   *
   * @return value of the <tt>leftWidget</tt> attribute
   */
  public Widget getLeftWidget();

  /**
   * Sets the <tt>leftWidget</tt> attribute.
   * <p>
   * the widget located to the left or above the divider
   * <p>
   *
   * @param  leftWidget value of the <tt>leftWidget</tt> attribute. 
   */
  public void setLeftWidget(Widget leftWidget);

  /**
   * see the {@link #getLeftWidget() getLeftWidget()} method
   */
  public Widget getTopWidget();

  /**
   * see the {@link #setLeftWidget(Widget) setLeftWidget(Widget)} method
   */
  public void setTopWidget(Widget leftWidget);

  /**
   * Returns the value of the <tt>rightWidget</tt> attribute.
   * <p>
   *
   * @return value of the <tt>rightWidget</tt> attribute
   */
  public Widget getRightWidget();

  /**
   * Sets the <tt>rightWidget</tt> attribute.
   * <p>
   *
   * @param  rightWidget value of the <tt>rightWidget</tt> attribute. 
   */
  public void setRightWidget(Widget rightWidget);

  /**
   * see the {@link #getRightWidget() getRightWidget()} method
   */
  public Widget getBottomWidget();

  /**
   * see the {@link #setRightWidget(Widget) setRightWidget(Widget)} method
   */
  public void setBottomWidget(Widget rightWidget);
}
