/*
 * Copyright (c) 2000-2002, Shayne R Flint
 * All rights reserved.
 * 
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *    * Redistributions of source code must retain the above copyright
 *      notice, this list of conditions and the following disclaimer.
 *
 *    * Redistributions in binary form must reproduce the above copyright
 *      notice, this list of conditions and the following disclaimer in the
 *      documentation and/or other materials provided with the distribution.
 *
 *    * The name of the author may not be used to endorse or promote products
 *      derived from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
 * IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
 * OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
 * IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
 * NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
 * THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/*
 * ./armidale/api/gui/Text.java
 * Generated by armidale.utilities.makeclass.Main armidale v0.9.5 on 10Apr2002 at 17:58:21
 *
 */

package armidale.api.gui;
  /**
   *
   * @author  generated by <tt>armidale.utilities.makeclass.Main</tt> on 10Apr2002 at 17:58:21
   * @version armidale v0.9.5
   */

public interface Text extends Widget {

  // Attributes Defaults
  //
  public static final String DEFAULT_TEXT = "";
  public static final boolean DEFAULT_EDITABLE = true;
  public static final Color DEFAULT_TEXT_BACKGROUNDCOLOR = Color.WHITE;

  // attribute set/get/is methods
  //

  /**
   * Returns the value of the <tt>text</tt> attribute.
   * <p>
   *
   * @return value of the <tt>text</tt> attribute
   */
  public String getText();

  /**
   * Sets the <tt>text</tt> attribute.
   * <p>
   *
   * @param  text value of the <tt>text</tt> attribute. 
   */
  public void setText(String text);

  /**
   * Returns the value of the <tt>editable</tt> attribute.
   * <p>
   *
   * @return value of the <tt>editable</tt> attribute
   */
  public boolean isEditable();

  /**
   * Sets the <tt>editable</tt> attribute.
   * <p>
   *
   * @param  editable value of the <tt>editable</tt> attribute. 
   */
  public void setEditable(boolean editable);

  // callback
  //

  /**
   * Registers a callback with this Text
   *
   * @param  callback callback to be added
   *
   */
  public void addTextCallback(TextCallback callback);

  /**
   * Removes a callback registered with this Text
   *
   * @param  callback callback to be removed
   */
  public void removeTextCallback(TextCallback callback);

  /**
   * Removes all callbacks registered with this Text
   *
   */
  public void removeAllTextCallbacks();

  /**
   * Returns the list of callbacks registered with this Text
   *
   * @return list of callbacks registered with this object
   */
  public TextCallbackList getTextCallbackList();
}
