/*
 * Copyright (c) 2000-2002, Shayne R Flint
 * All rights reserved.
 * 
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *    * Redistributions of source code must retain the above copyright
 *      notice, this list of conditions and the following disclaimer.
 *
 *    * Redistributions in binary form must reproduce the above copyright
 *      notice, this list of conditions and the following disclaimer in the
 *      documentation and/or other materials provided with the distribution.
 *
 *    * The name of the author may not be used to endorse or promote products
 *      derived from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
 * IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
 * OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
 * IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
 * NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
 * THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/*
 * ./armidale/api/gui/Toggle.java
 * Generated by armidale.utilities.makeclass.Main armidale v0.9.5 on 10Apr2002 at 17:57:57
 *
 */

package armidale.api.gui;
  /**
   *
   * @author  generated by <tt>armidale.utilities.makeclass.Main</tt> on 10Apr2002 at 17:57:57
   * @version armidale v0.9.5
   */

public interface Toggle extends Button {

  // Attributes Defaults
  //
  public static final boolean DEFAULT_SELECTED = false;

  // attribute set/get/is methods
  //

  /**
   * Returns the value of the <tt>selected</tt> attribute.
   * <p>
   *
   * @return value of the <tt>selected</tt> attribute
   */
  public boolean isSelected();

  /**
   * Sets the <tt>selected</tt> attribute.
   * <p>
   *
   * @param  selected value of the <tt>selected</tt> attribute. 
   */
  public void setSelected(boolean selected);

  // callback
  //

  /**
   * Registers a callback with this Toggle
   *
   * @param  callback callback to be added
   *
   */
  public void addToggleCallback(ToggleCallback callback);

  /**
   * Removes a callback registered with this Toggle
   *
   * @param  callback callback to be removed
   */
  public void removeToggleCallback(ToggleCallback callback);

  /**
   * Removes all callbacks registered with this Toggle
   *
   */
  public void removeAllToggleCallbacks();

  /**
   * Returns the list of callbacks registered with this Toggle
   *
   * @return list of callbacks registered with this object
   */
  public ToggleCallbackList getToggleCallbackList();
}
