/*
 * Copyright (c) 2000-2002, Shayne R Flint
 * All rights reserved.
 * 
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *    * Redistributions of source code must retain the above copyright
 *      notice, this list of conditions and the following disclaimer.
 *
 *    * Redistributions in binary form must reproduce the above copyright
 *      notice, this list of conditions and the following disclaimer in the
 *      documentation and/or other materials provided with the distribution.
 *
 *    * The name of the author may not be used to endorse or promote products
 *      derived from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
 * IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
 * OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
 * IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
 * NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
 * THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/*
 * ./armidale/api/gui/Widget.java
 * Generated by armidale.utilities.makeclass.Main armidale v0.9.5 on 10Apr2002 at 17:57:48
 *
 */

package armidale.api.gui;
  /**
   *
   * @author  generated by <tt>armidale.utilities.makeclass.Main</tt> on 10Apr2002 at 17:57:48
   * @version armidale v0.9.5
   */

public interface Widget extends Component {

  // Attributes Defaults
  //
  public static final float DEFAULT_ALIGNMENTX = 0.5f;
  public static final float DEFAULT_ALIGNMENTY = 0.5f;

  // attribute set/get/is methods
  //

  /**
   * Sets the <tt>preferredSize</tt> attribute.
   * <p>
   *
   * @param  preferredSize value of the <tt>preferredSize</tt> attribute. 
   */
  public void setPreferredSize(Size preferredSize);

  /**
   * Sets the <tt>minimumSize</tt> attribute.
   * <p>
   *
   * @param  minimumSize value of the <tt>minimumSize</tt> attribute. 
   */
  public void setMinimumSize(Size minimumSize);

  /**
   * Sets the <tt>maximumSize</tt> attribute.
   * <p>
   *
   * @param  maximumSize value of the <tt>maximumSize</tt> attribute. 
   */
  public void setMaximumSize(Size maximumSize);

  /**
   * Returns the value of the <tt>alignmentX</tt> attribute.
   * <p>
   *
   * @return value of the <tt>alignmentX</tt> attribute
   */
  public float getAlignmentX();

  /**
   * Sets the <tt>alignmentX</tt> attribute.
   * <p>
   *
   * @param  alignmentX value of the <tt>alignmentX</tt> attribute. 
   */
  public void setAlignmentX(float alignmentX);

  /**
   * Returns the value of the <tt>alignmentY</tt> attribute.
   * <p>
   *
   * @return value of the <tt>alignmentY</tt> attribute
   */
  public float getAlignmentY();

  /**
   * Sets the <tt>alignmentY</tt> attribute.
   * <p>
   *
   * @param  alignmentY value of the <tt>alignmentY</tt> attribute. 
   */
  public void setAlignmentY(float alignmentY);

  // other methods
  //

  /**
   *
   * @param size
   */
  public void setSize(Size size);
}
