/*
 * Copyright (c) 2000-2002, Shayne R Flint
 * All rights reserved.
 * 
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *    * Redistributions of source code must retain the above copyright
 *      notice, this list of conditions and the following disclaimer.
 *
 *    * Redistributions in binary form must reproduce the above copyright
 *      notice, this list of conditions and the following disclaimer in the
 *      documentation and/or other materials provided with the distribution.
 *
 *    * The name of the author may not be used to endorse or promote products
 *      derived from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
 * IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
 * OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
 * IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
 * NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
 * THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/*
 * ./armidale/api/gui/WindowCallbackDebug.java
 * Generated by armidale.utilities.makeclass.Main armidale v0.9.5 on 10Apr2002 at 17:58:25
 *
 */

package armidale.api.gui;

  import armidale.api.context.Context;
  import armidale.api.io.Debug;

  /**
   * An implementation of the {@link armidale.api.gui.WindowCallback WindowCallback} interface.
   * All methods in this class call the {@link armidale.api.io.Debug Debug} class with a message describing
   * the method called. The class exists as a convenience for debugging callbacks.
   */

public class WindowCallbackDebug implements WindowCallback {

  private Debug debug;
  private int   debugLevel;

  /**
   * Constructor which creates an object that will display messages on the specified context's output
   * when the current debug level is >= a specified level.
   *
   * @param context the context for display of messages (see {@link armidale.api.context.Context Context}
   * @param debugLevel the debug level (see {@link armidale.api.io.Debug Debug}
   */
  public WindowCallbackDebug(Context context, int debugLevel) {
    super();
    debug = new Debug(context.getTextOutput());
    this.debugLevel = debugLevel;
  }

  /**
   * Constructor which creates an object that will display messages on the specified context's output
   * irrespective of debug level.
   *
   * @param context the context for display of messages (see {@link armidale.api.context.Context Context}
   */
  public WindowCallbackDebug(Context context) {
    debug = new Debug(context.getTextOutput());
    this.debugLevel = Debug.ALLWAYS;
  }

  /**
   * @see armidale.api.gui.WindowCallback#windowOpen
   */
  public void windowOpen(Window window) {
    debug.message("WindowCallback.windowOpen" , new String[] {this.toString(), window.toString()}, debugLevel);
  }

  /**
   * @see armidale.api.gui.WindowCallback#windowActivated
   */
  public void windowActivated(Window window) {
    debug.message("WindowCallback.windowActivated" , new String[] {this.toString(), window.toString()}, debugLevel);
  }

  /**
   * @see armidale.api.gui.WindowCallback#windowClosed
   */
  public void windowClosed(Window window) {
    debug.message("WindowCallback.windowClosed" , new String[] {this.toString(), window.toString()}, debugLevel);
  }

  /**
   * @see armidale.api.gui.WindowCallback#windowClosing
   */
  public void windowClosing(Window window) {
    debug.message("WindowCallback.windowClosing" , new String[] {this.toString(), window.toString()}, debugLevel);
  }

  /**
   * @see armidale.api.gui.WindowCallback#windowDeactivated
   */
  public void windowDeactivated(Window window) {
    debug.message("WindowCallback.windowDeactivated" , new String[] {this.toString(), window.toString()}, debugLevel);
  }

  /**
   * @see armidale.api.gui.WindowCallback#windowDeiconified
   */
  public void windowDeiconified(Window window) {
    debug.message("WindowCallback.windowDeiconified" , new String[] {this.toString(), window.toString()}, debugLevel);
  }

  /**
   * @see armidale.api.gui.WindowCallback#windowIconified
   */
  public void windowIconified(Window window) {
    debug.message("WindowCallback.windowIconified" , new String[] {this.toString(), window.toString()}, debugLevel);
  }

  /**
   * @see armidale.api.gui.WindowCallback#windowOpened
   */
  public void windowOpened(Window window) {
    debug.message("WindowCallback.windowOpened" , new String[] {this.toString(), window.toString()}, debugLevel);
  }

  /**
   * @see armidale.api.gui.WindowCallback#windowMoved
   */
  public void windowMoved(Window window, Position position) {
    debug.message("WindowCallback.windowMoved" , new String[] {this.toString(), window.toString(), "position = " + position.toString()}, debugLevel);
  }

  /**
   * @see armidale.api.gui.WindowCallback#windowResized
   */
  public void windowResized(Window window, Size size) {
    debug.message("WindowCallback.windowResized" , new String[] {this.toString(), window.toString(), "size = " + size.toString()}, debugLevel);
  }

}
