/*
 * Copyright (c) 2000-2002, Shayne R Flint
 * All rights reserved.
 * 
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *    * Redistributions of source code must retain the above copyright
 *      notice, this list of conditions and the following disclaimer.
 *
 *    * Redistributions in binary form must reproduce the above copyright
 *      notice, this list of conditions and the following disclaimer in the
 *      documentation and/or other materials provided with the distribution.
 *
 *    * The name of the author may not be used to endorse or promote products
 *      derived from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
 * IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
 * OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
 * IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
 * NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
 * THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/*
 * ./armidale/api/gui/impl/clientserver/ActionClientImpl.java
 * Generated by armidale.utilities.makeclass.Main armidale v0.9.5 on 10Apr2002 at 17:57:49
 *
 */

package armidale.api.gui.impl.clientserver;

  import armidale.api.ImplementationException;
  import armidale.api.context.clientserver.*;
  import armidale.api.gui.Action;
  import armidale.api.gui.ActionCallback;
  import armidale.api.gui.ActionCallbackList;

public abstract class ActionClientImpl extends WidgetClientImpl implements ActionClientServerIds {

  // constructor
  //
  public ActionClientImpl(ClientContext context, Action peer) {
    super(context, peer);
  }

  // Callback methods
  //

  public void addActionCallback(ActionCallback callback) {
    ((Action)peer).addActionCallback(callback);
  }

  public void removeActionCallback(ActionCallback callback) {
    ((Action)peer).removeActionCallback(callback);
  }

  public void removeAllActionCallbacks() {
    ((Action)peer).removeAllActionCallbacks();
  }

  public ActionCallbackList getActionCallbackList() {
    throw new ImplementationException("callback get methods are not supported in client context");
  }

  // local callback handlers
  //

  private class LocalCallback implements ActionCallback {

    public void actionPerformed(Action action) {
      Message message = new CallbackMessage(ActionClientImpl.this.getId(), actionActionPerformedId);
      transport.writeMessage(message);
    }
  }

  public void handleEnableCallbacks() {
    addActionCallback(new LocalCallback());
  }

  public void handleDisableCallbacks() {
    removeAllActionCallbacks();
  }
}
