/*
 * Copyright (c) 2000-2002, Shayne R Flint
 * All rights reserved.
 * 
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *    * Redistributions of source code must retain the above copyright
 *      notice, this list of conditions and the following disclaimer.
 *
 *    * Redistributions in binary form must reproduce the above copyright
 *      notice, this list of conditions and the following disclaimer in the
 *      documentation and/or other materials provided with the distribution.
 *
 *    * The name of the author may not be used to endorse or promote products
 *      derived from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
 * IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
 * OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
 * IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
 * NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
 * THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/*
 * ./armidale/api/gui/impl/clientserver/BorderPanelServerImpl.java
 * Generated by armidale.utilities.makeclass.Main armidale v0.9.5 on 10Apr2002 at 17:58:07
 *
 */

package armidale.api.gui.impl.clientserver;

  import armidale.api.context.clientserver.*;
  import armidale.api.gui.BorderPanelFactory;
  import armidale.api.gui.BorderPanelWidget;
  import java.io.IOException;

public class BorderPanelServerImpl extends PanelServerImpl implements BorderPanelClientServerIds {

  // readable attributes
  //
  protected int horizontalGap = DEFAULT_HORIZONTALGAP;
  protected int verticalGap = DEFAULT_VERTICALGAP;

  // constructor
  //
  public BorderPanelServerImpl(ServerContext context) {
    super(context);
  }

  // Class ID
  //
  public int getClassId() {
    return BorderPanelFactory.CLASS_ID;
  }

  // attribute set/get/is methods
  //

  public int getHorizontalGap() {
    return horizontalGap;
  }

  public void setHorizontalGap(int horizontalGap) {
    this.horizontalGap = horizontalGap;
    Message msg = new SetAttributeMessage(this.getId(), horizontalGapId);
    msg.writeInt(horizontalGap);
    transport.writeMessage(msg);
  }

  public int getVerticalGap() {
    return verticalGap;
  }

  public void setVerticalGap(int verticalGap) {
    this.verticalGap = verticalGap;
    Message msg = new SetAttributeMessage(this.getId(), verticalGapId);
    msg.writeInt(verticalGap);
    transport.writeMessage(msg);
  }

  // other methods
  //

  public void addWidget(BorderPanelWidget borderPanelWidget) {
    Message msg = new MethodCallMessage(this.getId(), addWidgetBorderPanelWidgetId);
    msg.writeObjectId((MessagingObject)borderPanelWidget);
    transport.writeMessage(msg);
  }

  public void removeWidget(BorderPanelWidget borderPanelWidget) {
    Message msg = new MethodCallMessage(this.getId(), removeWidgetBorderPanelWidgetId);
    msg.writeObjectId((MessagingObject)borderPanelWidget);
    transport.writeMessage(msg);
  }

  public void removeAllWidgets() {
    Message msg = new MethodCallMessage(this.getId(), removeAllWidgetsId);
    transport.writeMessage(msg);
  }

}
