/*
 * Copyright (c) 2000-2002, Shayne R Flint
 * All rights reserved.
 * 
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *    * Redistributions of source code must retain the above copyright
 *      notice, this list of conditions and the following disclaimer.
 *
 *    * Redistributions in binary form must reproduce the above copyright
 *      notice, this list of conditions and the following disclaimer in the
 *      documentation and/or other materials provided with the distribution.
 *
 *    * The name of the author may not be used to endorse or promote products
 *      derived from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
 * IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
 * OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
 * IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
 * NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
 * THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/*
 * ./armidale/api/gui/impl/clientserver/BorderPanelClientImpl.java
 * Generated by armidale.utilities.makeclass.Main armidale v0.9.5 on 10Apr2002 at 17:58:07
 *
 */

package armidale.api.gui.impl.clientserver;

  import armidale.api.ImplementationException;
  import armidale.api.context.clientserver.*;
  import armidale.api.gui.BorderPanel;
  import armidale.api.gui.BorderPanelFactory;
  import armidale.api.gui.BorderPanelWidget;

public class BorderPanelClientImpl extends PanelClientImpl implements BorderPanelClientServerIds {

  // constructor
  //
  public BorderPanelClientImpl(ClientContext context, BorderPanel peer) {
    super(context, peer);
  }

  // Class ID
  //
  public int getClassId() {
    return BorderPanelFactory.CLASS_ID;
  }

  // attribute set/get/is methods
  //

  public int getHorizontalGap() {
    throw new ImplementationException("attribute get/is methods are not supported in client context");
  }

  public void setHorizontalGap(int horizontalGap) {
    ((BorderPanel)peer).setHorizontalGap(horizontalGap);
  }

  public int getVerticalGap() {
    throw new ImplementationException("attribute get/is methods are not supported in client context");
  }

  public void setVerticalGap(int verticalGap) {
    ((BorderPanel)peer).setVerticalGap(verticalGap);
  }

  // other methods
  //

  public void addWidget(BorderPanelWidget borderPanelWidget) {
    BorderPanelWidget borderPanelWidgetPeer;
    if (borderPanelWidget==null) {
     borderPanelWidgetPeer = null;
    } else {
     borderPanelWidgetPeer = (BorderPanelWidget)((BorderPanelWidgetClientImpl)borderPanelWidget).peer;
    }
    ((BorderPanel)peer).addWidget(borderPanelWidgetPeer);
  }

  public void removeWidget(BorderPanelWidget borderPanelWidget) {
    BorderPanelWidget borderPanelWidgetPeer;
    if (borderPanelWidget==null) {
     borderPanelWidgetPeer = null;
    } else {
     borderPanelWidgetPeer = (BorderPanelWidget)((BorderPanelWidgetClientImpl)borderPanelWidget).peer;
    }
    ((BorderPanel)peer).removeWidget(borderPanelWidgetPeer);
  }

  public void removeAllWidgets() {
    ((BorderPanel)peer).removeAllWidgets();
  }

  public void handleSetAttribute(int attributeId, Message message) {
    int index;
    int first;
    int count;

    switch (attributeId) {
      case horizontalGapId:
        setHorizontalGap(message.readInt());
        break;
      case verticalGapId:
        setVerticalGap(message.readInt());
        break;
      default:
        super.handleSetAttribute(attributeId, message);
    }
  }

  public void handleMethodCall(int methodId, Message message) {

    // method parameter values
    //
    BorderPanelWidget addWidgetBorderPanelWidget;
    BorderPanelWidget removeWidgetBorderPanelWidget;

    switch (methodId) {
      case addWidgetBorderPanelWidgetId:
        addWidgetBorderPanelWidget = (BorderPanelWidget)objectRegistry.findObject(message.readObjectId());
        addWidget(addWidgetBorderPanelWidget);
        break;
      case removeWidgetBorderPanelWidgetId:
        removeWidgetBorderPanelWidget = (BorderPanelWidget)objectRegistry.findObject(message.readObjectId());
        removeWidget(removeWidgetBorderPanelWidget);
        break;
      case removeAllWidgetsId:
        removeAllWidgets();
        break;
      default:
        super.handleMethodCall(methodId, message);
    }
  }
}
