/*
 * Copyright (c) 2000-2002, Shayne R Flint
 * All rights reserved.
 * 
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *    * Redistributions of source code must retain the above copyright
 *      notice, this list of conditions and the following disclaimer.
 *
 *    * Redistributions in binary form must reproduce the above copyright
 *      notice, this list of conditions and the following disclaimer in the
 *      documentation and/or other materials provided with the distribution.
 *
 *    * The name of the author may not be used to endorse or promote products
 *      derived from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
 * IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
 * OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
 * IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
 * NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
 * THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/*
 * ./armidale/api/gui/impl/clientserver/ComponentClientImpl.java
 * Generated by armidale.utilities.makeclass.Main armidale v0.9.5 on 10Apr2002 at 17:57:45
 *
 */

package armidale.api.gui.impl.clientserver;

  import armidale.api.ImplementationException;
  import armidale.api.context.clientserver.*;
  import armidale.api.gui.Color;
  import armidale.api.gui.Component;
  import armidale.api.gui.Font;
  import armidale.api.gui.PopupMenu;
  import armidale.api.gui.constants.CursorType;

public abstract class ComponentClientImpl extends VisibleObjectClientImpl implements ComponentClientServerIds {

  // constructor
  //
  public ComponentClientImpl(ClientContext context, Component peer) {
    super(context, peer);
  }

  // attribute set/get/is methods
  //

  public boolean isEnabled() {
    throw new ImplementationException("attribute get/is methods are not supported in client context");
  }

  public void setEnabled(boolean enabled) {
    ((Component)peer).setEnabled(enabled);
  }

  public String getToolTip() {
    throw new ImplementationException("attribute get/is methods are not supported in client context");
  }

  public void setToolTip(String toolTip) {
    ((Component)peer).setToolTip(toolTip);
  }

  public PopupMenu getPopupMenu() {
    throw new ImplementationException("attribute get/is methods are not supported in client context");
  }

  public void setPopupMenu(PopupMenu popupMenu) {
    if (popupMenu==null) {
      ((Component)peer).setPopupMenu(null);
    } else {
      ((Component)peer).setPopupMenu((PopupMenu)((PopupMenuClientImpl)popupMenu).peer);
    }
  }

  public Font getFont() {
    throw new ImplementationException("attribute get/is methods are not supported in client context");
  }

  public void setFont(Font font) {
    ((Component)peer).setFont(font);
  }

  public Color getForegroundColor() {
    throw new ImplementationException("attribute get/is methods are not supported in client context");
  }

  public void setForegroundColor(Color foregroundColor) {
    ((Component)peer).setForegroundColor(foregroundColor);
  }

  public Color getBackgroundColor() {
    throw new ImplementationException("attribute get/is methods are not supported in client context");
  }

  public void setBackgroundColor(Color backgroundColor) {
    ((Component)peer).setBackgroundColor(backgroundColor);
  }

  public int getCursorType() {
    throw new ImplementationException("attribute get/is methods are not supported in client context");
  }

  public void setCursorType(int cursorType) {
    ((Component)peer).setCursorType(cursorType);
  }

  public void handleSetAttribute(int attributeId, Message message) {
    int index;
    int first;
    int count;

    switch (attributeId) {
      case enabledId:
        setEnabled(message.readBoolean());
        break;
      case toolTipId:
        setToolTip(message.readString());
        break;
      case popupMenuId:
        setPopupMenu((PopupMenu)objectRegistry.findObject(message.readObjectId()));
        break;
      case fontId:
        setFont(message.readFont());
        break;
      case foregroundColorId:
        setForegroundColor(message.readColor());
        break;
      case backgroundColorId:
        setBackgroundColor(message.readColor());
        break;
      case cursorTypeId:
        setCursorType(message.readInt());
        break;
      default:
        super.handleSetAttribute(attributeId, message);
    }
  }
}
