/*
 * Copyright (c) 2000-2002, Shayne R Flint
 * All rights reserved.
 * 
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *    * Redistributions of source code must retain the above copyright
 *      notice, this list of conditions and the following disclaimer.
 *
 *    * Redistributions in binary form must reproduce the above copyright
 *      notice, this list of conditions and the following disclaimer in the
 *      documentation and/or other materials provided with the distribution.
 *
 *    * The name of the author may not be used to endorse or promote products
 *      derived from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
 * IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
 * OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
 * IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
 * NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
 * THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/*
 * ./armidale/api/gui/impl/clientserver/DesktopClientImpl.java
 * Generated by armidale.utilities.makeclass.Main armidale v0.9.5 on 10Apr2002 at 17:58:02
 *
 */

package armidale.api.gui.impl.clientserver;

  import armidale.api.ImplementationException;
  import armidale.api.context.clientserver.*;
  import armidale.api.gui.Desktop;
  import armidale.api.gui.DesktopFactory;
  import armidale.api.gui.Image;
  import armidale.api.gui.InternalFrame;
  import armidale.api.gui.constants.WallpaperModes;

public class DesktopClientImpl extends WidgetClientImpl implements DesktopClientServerIds {

  // constructor
  //
  public DesktopClientImpl(ClientContext context, Desktop peer) {
    super(context, peer);
  }

  // Class ID
  //
  public int getClassId() {
    return DesktopFactory.CLASS_ID;
  }

  // attribute set/get/is methods
  //

  public Image getWallpaper() {
    throw new ImplementationException("attribute get/is methods are not supported in client context");
  }

  public void setWallpaper(Image wallpaper) {
    if (wallpaper==null) {
      ((Desktop)peer).setWallpaper(null);
    } else {
      ((Desktop)peer).setWallpaper((Image)((ImageClientImpl)wallpaper).peer);
    }
  }

  public int getWallpaperMode() {
    throw new ImplementationException("attribute get/is methods are not supported in client context");
  }

  public void setWallpaperMode(int wallpaperMode) {
    ((Desktop)peer).setWallpaperMode(wallpaperMode);
  }

  // other methods
  //

  public void addInternalFrame(InternalFrame internalFrame) {
    InternalFrame internalFramePeer;
    if (internalFrame==null) {
     internalFramePeer = null;
    } else {
     internalFramePeer = (InternalFrame)((InternalFrameClientImpl)internalFrame).peer;
    }
    ((Desktop)peer).addInternalFrame(internalFramePeer);
  }

  public void removeInternalFrame(InternalFrame internalFrame) {
    InternalFrame internalFramePeer;
    if (internalFrame==null) {
     internalFramePeer = null;
    } else {
     internalFramePeer = (InternalFrame)((InternalFrameClientImpl)internalFrame).peer;
    }
    ((Desktop)peer).removeInternalFrame(internalFramePeer);
  }

  public void removeAllInternalFrames() {
    ((Desktop)peer).removeAllInternalFrames();
  }

  public void handleSetAttribute(int attributeId, Message message) {
    int index;
    int first;
    int count;

    switch (attributeId) {
      case wallpaperId:
        setWallpaper((Image)objectRegistry.findObject(message.readObjectId()));
        break;
      case wallpaperModeId:
        setWallpaperMode(message.readInt());
        break;
      default:
        super.handleSetAttribute(attributeId, message);
    }
  }

  public void handleMethodCall(int methodId, Message message) {

    // method parameter values
    //
    InternalFrame addInternalFrameInternalFrame;
    InternalFrame removeInternalFrameInternalFrame;

    switch (methodId) {
      case addInternalFrameInternalFrameId:
        addInternalFrameInternalFrame = (InternalFrame)objectRegistry.findObject(message.readObjectId());
        addInternalFrame(addInternalFrameInternalFrame);
        break;
      case removeInternalFrameInternalFrameId:
        removeInternalFrameInternalFrame = (InternalFrame)objectRegistry.findObject(message.readObjectId());
        removeInternalFrame(removeInternalFrameInternalFrame);
        break;
      case removeAllInternalFramesId:
        removeAllInternalFrames();
        break;
      default:
        super.handleMethodCall(methodId, message);
    }
  }
}
