/*
 * Copyright (c) 2000-2002, Shayne R Flint
 * All rights reserved.
 * 
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *    * Redistributions of source code must retain the above copyright
 *      notice, this list of conditions and the following disclaimer.
 *
 *    * Redistributions in binary form must reproduce the above copyright
 *      notice, this list of conditions and the following disclaimer in the
 *      documentation and/or other materials provided with the distribution.
 *
 *    * The name of the author may not be used to endorse or promote products
 *      derived from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
 * IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
 * OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
 * IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
 * NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
 * THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/*
 * ./armidale/api/gui/impl/clientserver/DesktopServerImpl.java
 * Generated by armidale.utilities.makeclass.Main armidale v0.9.5 on 10Apr2002 at 17:58:02
 *
 */

package armidale.api.gui.impl.clientserver;

  import armidale.api.context.clientserver.*;
  import armidale.api.gui.DesktopFactory;
  import armidale.api.gui.Image;
  import armidale.api.gui.InternalFrame;
  import armidale.api.gui.constants.WallpaperModes;
  import java.io.IOException;

public class DesktopServerImpl extends WidgetServerImpl implements DesktopClientServerIds {

  // readable attributes
  //
  protected Image wallpaper;
  protected int wallpaperMode = DEFAULT_WALLPAPERMODE;

  // constructor
  //
  public DesktopServerImpl(ServerContext context) {
    super(context);
  }

  // Class ID
  //
  public int getClassId() {
    return DesktopFactory.CLASS_ID;
  }

  // attribute set/get/is methods
  //

  public Image getWallpaper() {
    return wallpaper;
  }

  public void setWallpaper(Image wallpaper) {
    this.wallpaper = wallpaper;
    Message msg = new SetAttributeMessage(this.getId(), wallpaperId);
    msg.writeObjectId((MessagingObject)wallpaper);
    transport.writeMessage(msg);
  }

  public int getWallpaperMode() {
    return wallpaperMode;
  }

  public void setWallpaperMode(int wallpaperMode) {
    this.wallpaperMode = wallpaperMode;
    Message msg = new SetAttributeMessage(this.getId(), wallpaperModeId);
    msg.writeInt(wallpaperMode);
    transport.writeMessage(msg);
  }

  // other methods
  //

  public void addInternalFrame(InternalFrame internalFrame) {
    Message msg = new MethodCallMessage(this.getId(), addInternalFrameInternalFrameId);
    msg.writeObjectId((MessagingObject)internalFrame);
    transport.writeMessage(msg);
  }

  public void removeInternalFrame(InternalFrame internalFrame) {
    Message msg = new MethodCallMessage(this.getId(), removeInternalFrameInternalFrameId);
    msg.writeObjectId((MessagingObject)internalFrame);
    transport.writeMessage(msg);
  }

  public void removeAllInternalFrames() {
    Message msg = new MethodCallMessage(this.getId(), removeAllInternalFramesId);
    transport.writeMessage(msg);
  }

}
