/*
 * Copyright (c) 2000-2002, Shayne R Flint
 * All rights reserved.
 * 
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *    * Redistributions of source code must retain the above copyright
 *      notice, this list of conditions and the following disclaimer.
 *
 *    * Redistributions in binary form must reproduce the above copyright
 *      notice, this list of conditions and the following disclaimer in the
 *      documentation and/or other materials provided with the distribution.
 *
 *    * The name of the author may not be used to endorse or promote products
 *      derived from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
 * IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
 * OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
 * IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
 * NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
 * THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/*
 * ./armidale/api/gui/impl/clientserver/GridPanelClientImpl.java
 * Generated by armidale.utilities.makeclass.Main armidale v0.9.5 on 10Apr2002 at 17:58:10
 *
 */

package armidale.api.gui.impl.clientserver;

  import armidale.api.ImplementationException;
  import armidale.api.context.clientserver.*;
  import armidale.api.gui.GridPanel;
  import armidale.api.gui.GridPanelFactory;
  import armidale.api.gui.GridPanelWidget;

public class GridPanelClientImpl extends PanelClientImpl implements GridPanelClientServerIds {

  // constructor
  //
  public GridPanelClientImpl(ClientContext context, GridPanel peer) {
    super(context, peer);
  }

  // Class ID
  //
  public int getClassId() {
    return GridPanelFactory.CLASS_ID;
  }

  // other methods
  //

  public void addWidget(GridPanelWidget gridPanelWidget) {
    GridPanelWidget gridPanelWidgetPeer;
    if (gridPanelWidget==null) {
     gridPanelWidgetPeer = null;
    } else {
     gridPanelWidgetPeer = (GridPanelWidget)((GridPanelWidgetClientImpl)gridPanelWidget).peer;
    }
    ((GridPanel)peer).addWidget(gridPanelWidgetPeer);
  }

  public void removeWidget(GridPanelWidget gridPanelWidget) {
    GridPanelWidget gridPanelWidgetPeer;
    if (gridPanelWidget==null) {
     gridPanelWidgetPeer = null;
    } else {
     gridPanelWidgetPeer = (GridPanelWidget)((GridPanelWidgetClientImpl)gridPanelWidget).peer;
    }
    ((GridPanel)peer).removeWidget(gridPanelWidgetPeer);
  }

  public void removeAllWidgets() {
    ((GridPanel)peer).removeAllWidgets();
  }

  public void handleSetAttribute(int attributeId, Message message) {
    int index;
    int first;
    int count;

    switch (attributeId) {
      default:
        super.handleSetAttribute(attributeId, message);
    }
  }

  public void handleMethodCall(int methodId, Message message) {

    // method parameter values
    //
    GridPanelWidget addWidgetGridPanelWidget;
    GridPanelWidget removeWidgetGridPanelWidget;

    switch (methodId) {
      case addWidgetGridPanelWidgetId:
        addWidgetGridPanelWidget = (GridPanelWidget)objectRegistry.findObject(message.readObjectId());
        addWidget(addWidgetGridPanelWidget);
        break;
      case removeWidgetGridPanelWidgetId:
        removeWidgetGridPanelWidget = (GridPanelWidget)objectRegistry.findObject(message.readObjectId());
        removeWidget(removeWidgetGridPanelWidget);
        break;
      case removeAllWidgetsId:
        removeAllWidgets();
        break;
      default:
        super.handleMethodCall(methodId, message);
    }
  }
}
