/*
 * Copyright (c) 2000-2002, Shayne R Flint
 * All rights reserved.
 * 
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *    * Redistributions of source code must retain the above copyright
 *      notice, this list of conditions and the following disclaimer.
 *
 *    * Redistributions in binary form must reproduce the above copyright
 *      notice, this list of conditions and the following disclaimer in the
 *      documentation and/or other materials provided with the distribution.
 *
 *    * The name of the author may not be used to endorse or promote products
 *      derived from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
 * IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
 * OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
 * IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
 * NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
 * THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/*
 * ./armidale/api/gui/impl/clientserver/ImageServerImpl.java
 * Generated by armidale.utilities.makeclass.Main armidale v0.9.5 on 10Apr2002 at 17:57:42
 *
 */

package armidale.api.gui.impl.clientserver;

  import armidale.api.context.clientserver.*;
  import armidale.api.gui.ImageCallback;
  import armidale.api.gui.ImageCallbackList;
  import armidale.api.gui.ImageFactory;
  import armidale.api.gui.Size;
  import armidale.api.impl.clientserver.ArmidaleObjectServerImpl;
  import armidale.api.io.File;
  import armidale.api.structures.ByteArray;
  import java.io.IOException;
  import java.util.LinkedList;

public class ImageServerImpl extends ArmidaleObjectServerImpl implements ImageClientServerIds {

  // readable attributes
  //
  protected Size size;
  protected String description = DEFAULT_DESCRIPTION;

  // Callback object
  //

  protected ImageCallbackList imageCallbackList = new ImageCallbackList();

  // constructor
  //
  public ImageServerImpl(ServerContext context) {
    super(context);
  }

  // Class ID
  //
  public int getClassId() {
    return ImageFactory.CLASS_ID;
  }

  // attribute set/get/is methods
  //

  public void setImageData(ByteArray imageData) {
    Message msg = new SetAttributeMessage(this.getId(), imageDataId);
    msg.writeByteArray(imageData);
    transport.writeMessage(msg);
  }

  public Size getSize() {
    return size;
  }

  public void setSize(Size size) {
    this.size = size;
    Message msg = new SetAttributeMessage(this.getId(), sizeId);
    msg.writeSize(size);
    transport.writeMessage(msg);
  }

  public void setFile(File file) {
    Message msg = new SetFileAttributeMessage(this.getId(), fileId, file);
    transport.writeMessage(msg);
  }

  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
    Message msg = new SetAttributeMessage(this.getId(), descriptionId);
    msg.writeString(description);
    transport.writeMessage(msg);
  }

  // Callback
  //

  public void addImageCallback(ImageCallback callback) {
    Message msg;
    imageCallbackList.add(callback);
    if (imageCallbackList.size() == 1) {
      msg = new EnableCallbacksMessage(this.getId());
      transport.writeMessage(msg);
    }
  }

  public void removeImageCallback(ImageCallback callback) {
    Message msg;
    imageCallbackList.remove(callback);
    if (imageCallbackList.size() == 0) {
      msg = new DisableCallbacksMessage(this.getId());
      transport.writeMessage(msg);
    }
  }

  public void removeAllImageCallbacks() {
    Message msg;
    imageCallbackList.clear();
    msg = new DisableCallbacksMessage(this.getId());
    transport.writeMessage(msg);
  }

  public ImageCallbackList getImageCallbackList() {
    return imageCallbackList;
  }

  // transport
  //

  public void handleCallback(int callbackMethodId, Message message) {
    String getFileFilename;

    switch (callbackMethodId) {
      case imageImageChangedId:
        imageCallbackList.imageChanged(this);
        break;
      case imageErrorId:
        imageCallbackList.error(this);
        break;
      case imageGetFileStringId:
        getFileFilename = message.readString();
        imageCallbackList.getFile(this, getFileFilename);
        break;
    }
  }

}
