/*
 * Copyright (c) 2000-2002, Shayne R Flint
 * All rights reserved.
 * 
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *    * Redistributions of source code must retain the above copyright
 *      notice, this list of conditions and the following disclaimer.
 *
 *    * Redistributions in binary form must reproduce the above copyright
 *      notice, this list of conditions and the following disclaimer in the
 *      documentation and/or other materials provided with the distribution.
 *
 *    * The name of the author may not be used to endorse or promote products
 *      derived from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
 * IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
 * OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
 * IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
 * NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
 * THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/*
 * ./armidale/api/gui/impl/clientserver/InternalFrameClientServerIds.java
 * Generated by armidale.utilities.makeclass.Main armidale v0.9.5 on 10Apr2002 at 17:58:27
 *
 */

package armidale.api.gui.impl.clientserver;

  import armidale.api.context.clientserver.*;
  import armidale.api.gui.InternalFrame;
  import armidale.api.gui.InternalFrameFactory;

  /**
   * Defines various constants used in communications between {@link armidale.api.gui.InternalFrame InternalFrame} clients and servers
   */

public interface InternalFrameClientServerIds extends InternalFrame {

  public final static int BASE_ID = InternalFrameFactory.CLASS_ID + 1;

  // Attribute IDs
  //
  public static final int sizeId = BASE_ID + 0;
  public static final int positionId = BASE_ID + 1;
  public static final int resizableId = BASE_ID + 2;
  public static final int closableId = BASE_ID + 3;
  public static final int maximizableId = BASE_ID + 4;
  public static final int iconifiableId = BASE_ID + 5;
  public static final int titleId = BASE_ID + 6;
  public static final int contentId = BASE_ID + 7;
  public static final int iconId = BASE_ID + 8;
  public static final int menubarId = BASE_ID + 9;
  public static final int toolbarId = BASE_ID + 10;
  public static final int statusbarId = BASE_ID + 11;
  public static final int backgroundColorId = BASE_ID + 12;

  // Other Method IDs
  //
  public static final int setAlignmentFloatFloatId = BASE_ID + 13;
  public static final int setAlignmentIntId = BASE_ID + 14;
}
