/*
 * Copyright (c) 2000-2002, Shayne R Flint
 * All rights reserved.
 * 
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *    * Redistributions of source code must retain the above copyright
 *      notice, this list of conditions and the following disclaimer.
 *
 *    * Redistributions in binary form must reproduce the above copyright
 *      notice, this list of conditions and the following disclaimer in the
 *      documentation and/or other materials provided with the distribution.
 *
 *    * The name of the author may not be used to endorse or promote products
 *      derived from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
 * IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
 * OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
 * IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
 * NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
 * THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/*
 * ./armidale/api/gui/impl/clientserver/LabeledWidgetClientImpl.java
 * Generated by armidale.utilities.makeclass.Main armidale v0.9.5 on 10Apr2002 at 17:58:03
 *
 */

package armidale.api.gui.impl.clientserver;

  import armidale.api.ImplementationException;
  import armidale.api.context.clientserver.*;
  import armidale.api.gui.Image;
  import armidale.api.gui.LabeledWidget;
  import armidale.api.gui.LabeledWidgetFactory;
  import armidale.api.gui.Widget;
  import armidale.api.gui.constants.Compass;

public class LabeledWidgetClientImpl extends PanelClientImpl implements LabeledWidgetClientServerIds {

  // constructor
  //
  public LabeledWidgetClientImpl(ClientContext context, LabeledWidget peer) {
    super(context, peer);
  }

  // Class ID
  //
  public int getClassId() {
    return LabeledWidgetFactory.CLASS_ID;
  }

  // attribute set/get/is methods
  //

  public Image getImage() {
    throw new ImplementationException("attribute get/is methods are not supported in client context");
  }

  public void setImage(Image image) {
    if (image==null) {
      ((LabeledWidget)peer).setImage(null);
    } else {
      ((LabeledWidget)peer).setImage((Image)((ImageClientImpl)image).peer);
    }
  }

  public String getText() {
    throw new ImplementationException("attribute get/is methods are not supported in client context");
  }

  public void setText(String text) {
    ((LabeledWidget)peer).setText(text);
  }

  public Widget getWidget() {
    throw new ImplementationException("attribute get/is methods are not supported in client context");
  }

  public void setWidget(Widget widget) {
    if (widget==null) {
      ((LabeledWidget)peer).setWidget(null);
    } else {
      ((LabeledWidget)peer).setWidget((Widget)((WidgetClientImpl)widget).peer);
    }
  }

  public int getTextImageAlignment() {
    throw new ImplementationException("attribute get/is methods are not supported in client context");
  }

  public void setTextImageAlignment(int textImageAlignment) {
    ((LabeledWidget)peer).setTextImageAlignment(textImageAlignment);
  }

  public int getTextImageGap() {
    throw new ImplementationException("attribute get/is methods are not supported in client context");
  }

  public void setTextImageGap(int textImageGap) {
    ((LabeledWidget)peer).setTextImageGap(textImageGap);
  }

  public int getLabelWidgetAlignment() {
    throw new ImplementationException("attribute get/is methods are not supported in client context");
  }

  public void setLabelWidgetAlignment(int labelWidgetAlignment) {
    ((LabeledWidget)peer).setLabelWidgetAlignment(labelWidgetAlignment);
  }

  public int getLabelWidgetGap() {
    throw new ImplementationException("attribute get/is methods are not supported in client context");
  }

  public void setLabelWidgetGap(int labelWidgetGap) {
    ((LabeledWidget)peer).setLabelWidgetGap(labelWidgetGap);
  }

  public void handleSetAttribute(int attributeId, Message message) {
    int index;
    int first;
    int count;

    switch (attributeId) {
      case imageId:
        setImage((Image)objectRegistry.findObject(message.readObjectId()));
        break;
      case textId:
        setText(message.readString());
        break;
      case widgetId:
        setWidget((Widget)objectRegistry.findObject(message.readObjectId()));
        break;
      case textImageAlignmentId:
        setTextImageAlignment(message.readInt());
        break;
      case textImageGapId:
        setTextImageGap(message.readInt());
        break;
      case labelWidgetAlignmentId:
        setLabelWidgetAlignment(message.readInt());
        break;
      case labelWidgetGapId:
        setLabelWidgetGap(message.readInt());
        break;
      default:
        super.handleSetAttribute(attributeId, message);
    }
  }
}
