/*
 * Copyright (c) 2000-2002, Shayne R Flint
 * All rights reserved.
 * 
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *    * Redistributions of source code must retain the above copyright
 *      notice, this list of conditions and the following disclaimer.
 *
 *    * Redistributions in binary form must reproduce the above copyright
 *      notice, this list of conditions and the following disclaimer in the
 *      documentation and/or other materials provided with the distribution.
 *
 *    * The name of the author may not be used to endorse or promote products
 *      derived from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
 * IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
 * OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
 * IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
 * NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
 * THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/*
 * ./armidale/api/gui/impl/clientserver/ListDataServerImpl.java
 * Generated by armidale.utilities.makeclass.Main armidale v0.9.5 on 10Apr2002 at 17:58:32
 *
 */

package armidale.api.gui.impl.clientserver;

  import armidale.api.ArmidaleObject;
  import armidale.api.context.clientserver.*;
  import armidale.api.gui.ListDataCallback;
  import armidale.api.gui.ListDataCallbackList;
  import armidale.api.gui.ListDataFactory;
  import armidale.api.impl.clientserver.ArmidaleObjectServerImpl;
  import java.io.IOException;
  import java.util.LinkedList;

public class ListDataServerImpl extends ArmidaleObjectServerImpl implements ListDataClientServerIds {

  // Callback object
  //

  protected ListDataCallbackList listDataCallbackList = new ListDataCallbackList();

  // constructor
  //
  public ListDataServerImpl(ServerContext context) {
    super(context);
  }

  // Class ID
  //
  public int getClassId() {
    return ListDataFactory.CLASS_ID;
  }

  // Callback
  //

  public void addListDataCallback(ListDataCallback callback) {
    Message msg;
    listDataCallbackList.add(callback);
    if (listDataCallbackList.size() == 1) {
      msg = new EnableCallbacksMessage(this.getId());
      transport.writeMessage(msg);
    }
  }

  public void removeListDataCallback(ListDataCallback callback) {
    Message msg;
    listDataCallbackList.remove(callback);
    if (listDataCallbackList.size() == 0) {
      msg = new DisableCallbacksMessage(this.getId());
      transport.writeMessage(msg);
    }
  }

  public void removeAllListDataCallbacks() {
    Message msg;
    listDataCallbackList.clear();
    msg = new DisableCallbacksMessage(this.getId());
    transport.writeMessage(msg);
  }

  public ListDataCallbackList getListDataCallbackList() {
    return listDataCallbackList;
  }

  // other methods
  //

  public void setItemCount(int count) {
    Message msg = new MethodCallMessage(this.getId(), setItemCountIntId);
    msg.writeInt(count);
    transport.writeMessage(msg);
  }

  public void setItem(int index, ArmidaleObject armidaleObject) {
    Message msg = new MethodCallMessage(this.getId(), setItemIntArmidaleObjectId);
    msg.writeInt(index);
    msg.writeObjectId((MessagingObject)armidaleObject);
    transport.writeMessage(msg);
  }

  public void setItem(int index, int count, ArmidaleObject armidaleObject) {
    Message msg = new MethodCallMessage(this.getId(), setItemIntIntArmidaleObjectId);
    msg.writeInt(index);
    msg.writeInt(count);
    msg.writeObjectId((MessagingObject)armidaleObject);
    transport.writeMessage(msg);
  }

  public void setItems(int index, ArmidaleObject[] armidaleObjects) {
    Message msg = new MethodCallMessage(this.getId(), setItemsIntArmidaleObjectId);
    msg.writeInt(index);
    msg.writeInt(armidaleObjects.length);
    for (int i=0; i<armidaleObjects.length; i++) {
      msg.writeObjectId((MessagingObject)armidaleObjects[i]);
    }
    transport.writeMessage(msg);
  }

  public void insertItem(int index, ArmidaleObject armidaleObject) {
    Message msg = new MethodCallMessage(this.getId(), insertItemIntArmidaleObjectId);
    msg.writeInt(index);
    msg.writeObjectId((MessagingObject)armidaleObject);
    transport.writeMessage(msg);
  }

  public void insertItem(int index, int count, ArmidaleObject armidaleObject) {
    Message msg = new MethodCallMessage(this.getId(), insertItemIntIntArmidaleObjectId);
    msg.writeInt(index);
    msg.writeInt(count);
    msg.writeObjectId((MessagingObject)armidaleObject);
    transport.writeMessage(msg);
  }

  public void insertItems(int index, ArmidaleObject[] armidaleObjects) {
    Message msg = new MethodCallMessage(this.getId(), insertItemsIntArmidaleObjectId);
    msg.writeInt(index);
    msg.writeInt(armidaleObjects.length);
    for (int i=0; i<armidaleObjects.length; i++) {
      msg.writeObjectId((MessagingObject)armidaleObjects[i]);
    }
    transport.writeMessage(msg);
  }

  public void removeItem(int index) {
    Message msg = new MethodCallMessage(this.getId(), removeItemIntId);
    msg.writeInt(index);
    transport.writeMessage(msg);
  }

  public void removeItems(int index, int count) {
    Message msg = new MethodCallMessage(this.getId(), removeItemsIntIntId);
    msg.writeInt(index);
    msg.writeInt(count);
    transport.writeMessage(msg);
  }

  public void addItem(ArmidaleObject armidaleObject) {
    Message msg = new MethodCallMessage(this.getId(), addItemArmidaleObjectId);
    msg.writeObjectId((MessagingObject)armidaleObject);
    transport.writeMessage(msg);
  }

  public void removeItem(ArmidaleObject armidaleObject) {
    Message msg = new MethodCallMessage(this.getId(), removeItemArmidaleObjectId);
    msg.writeObjectId((MessagingObject)armidaleObject);
    transport.writeMessage(msg);
  }

  public void removeAllItems() {
    Message msg = new MethodCallMessage(this.getId(), removeAllItemsId);
    transport.writeMessage(msg);
  }

  // transport
  //

  public void handleCallback(int callbackMethodId, Message message) {
    int requestItemsFirst;
    int requestItemsCount;

    switch (callbackMethodId) {
      case listDataRequestItemsIntIntId:
        requestItemsFirst = message.readInt();
        requestItemsCount = message.readInt();
        listDataCallbackList.requestItems(this, requestItemsFirst, requestItemsCount);
        break;
    }
  }

}
