/*
 * Copyright (c) 2000-2002, Shayne R Flint
 * All rights reserved.
 * 
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *    * Redistributions of source code must retain the above copyright
 *      notice, this list of conditions and the following disclaimer.
 *
 *    * Redistributions in binary form must reproduce the above copyright
 *      notice, this list of conditions and the following disclaimer in the
 *      documentation and/or other materials provided with the distribution.
 *
 *    * The name of the author may not be used to endorse or promote products
 *      derived from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
 * IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
 * OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
 * IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
 * NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
 * THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/*
 * ./armidale/api/gui/impl/clientserver/ListBoxClientImpl.java
 * Generated by armidale.utilities.makeclass.Main armidale v0.9.5 on 10Apr2002 at 17:58:13
 *
 */

package armidale.api.gui.impl.clientserver;

  import armidale.api.ImplementationException;
  import armidale.api.context.clientserver.*;
  import armidale.api.gui.ListBox;
  import armidale.api.gui.ListBoxCallback;
  import armidale.api.gui.ListBoxCallbackList;
  import armidale.api.gui.ListBoxFactory;
  import armidale.api.gui.ListData;

public class ListBoxClientImpl extends WidgetClientImpl implements ListBoxClientServerIds {

  // constructor
  //
  public ListBoxClientImpl(ClientContext context, ListBox peer) {
    super(context, peer);
  }

  // Class ID
  //
  public int getClassId() {
    return ListBoxFactory.CLASS_ID;
  }

  // attribute set/get/is methods
  //

  public ListData getListData() {
    throw new ImplementationException("attribute get/is methods are not supported in client context");
  }

  public void setListData(ListData listData) {
    if (listData==null) {
      ((ListBox)peer).setListData(null);
    } else {
      ((ListBox)peer).setListData((ListData)((ListDataClientImpl)listData).peer);
    }
  }

  // Callback methods
  //

  public void addListBoxCallback(ListBoxCallback callback) {
    ((ListBox)peer).addListBoxCallback(callback);
  }

  public void removeListBoxCallback(ListBoxCallback callback) {
    ((ListBox)peer).removeListBoxCallback(callback);
  }

  public void removeAllListBoxCallbacks() {
    ((ListBox)peer).removeAllListBoxCallbacks();
  }

  public ListBoxCallbackList getListBoxCallbackList() {
    throw new ImplementationException("callback get methods are not supported in client context");
  }

  // local callback handlers
  //

  private class LocalCallback implements ListBoxCallback {

    public void itemsSelected(ListBox listBox, int[] indices) {
      Message message = new CallbackMessage(ListBoxClientImpl.this.getId(), listBoxItemsSelectedIntId);
      message.writeInt(indices.length);
      for (int i=0; i<indices.length; i++) {
        message.writeInt(indices[i]);
      }
      transport.writeMessage(message);
    }
  }

  public void handleSetAttribute(int attributeId, Message message) {
    int index;
    int first;
    int count;

    switch (attributeId) {
      case listDataId:
        setListData((ListData)objectRegistry.findObject(message.readObjectId()));
        break;
      default:
        super.handleSetAttribute(attributeId, message);
    }
  }

  public void handleEnableCallbacks() {
    addListBoxCallback(new LocalCallback());
  }

  public void handleDisableCallbacks() {
    removeAllListBoxCallbacks();
  }
}
