/*
 * Copyright (c) 2000-2002, Shayne R Flint
 * All rights reserved.
 * 
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *    * Redistributions of source code must retain the above copyright
 *      notice, this list of conditions and the following disclaimer.
 *
 *    * Redistributions in binary form must reproduce the above copyright
 *      notice, this list of conditions and the following disclaimer in the
 *      documentation and/or other materials provided with the distribution.
 *
 *    * The name of the author may not be used to endorse or promote products
 *      derived from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
 * IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
 * OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
 * IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
 * NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
 * THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/*
 * ./armidale/api/gui/impl/clientserver/PopupMenuClientImpl.java
 * Generated by armidale.utilities.makeclass.Main armidale v0.9.5 on 10Apr2002 at 17:57:47
 *
 */

package armidale.api.gui.impl.clientserver;

  import armidale.api.ImplementationException;
  import armidale.api.context.clientserver.*;
  import armidale.api.gui.MenuItem;
  import armidale.api.gui.PopupMenu;
  import armidale.api.gui.PopupMenuFactory;

public class PopupMenuClientImpl extends ComponentClientImpl implements PopupMenuClientServerIds {

  // constructor
  //
  public PopupMenuClientImpl(ClientContext context, PopupMenu peer) {
    super(context, peer);
  }

  // Class ID
  //
  public int getClassId() {
    return PopupMenuFactory.CLASS_ID;
  }

  // other methods
  //

  public void addMenuItem(MenuItem menuItem) {
    MenuItem menuItemPeer;
    if (menuItem==null) {
     menuItemPeer = null;
    } else {
     menuItemPeer = (MenuItem)((MenuItemClientImpl)menuItem).peer;
    }
    ((PopupMenu)peer).addMenuItem(menuItemPeer);
  }

  public void removeMenuItem(MenuItem menuItem) {
    MenuItem menuItemPeer;
    if (menuItem==null) {
     menuItemPeer = null;
    } else {
     menuItemPeer = (MenuItem)((MenuItemClientImpl)menuItem).peer;
    }
    ((PopupMenu)peer).removeMenuItem(menuItemPeer);
  }

  public void removeAllMenuItems() {
    ((PopupMenu)peer).removeAllMenuItems();
  }

  public void handleSetAttribute(int attributeId, Message message) {
    int index;
    int first;
    int count;

    switch (attributeId) {
      default:
        super.handleSetAttribute(attributeId, message);
    }
  }

  public void handleMethodCall(int methodId, Message message) {

    // method parameter values
    //
    MenuItem addMenuItemMenuItem;
    MenuItem removeMenuItemMenuItem;

    switch (methodId) {
      case addMenuItemMenuItemId:
        addMenuItemMenuItem = (MenuItem)objectRegistry.findObject(message.readObjectId());
        addMenuItem(addMenuItemMenuItem);
        break;
      case removeMenuItemMenuItemId:
        removeMenuItemMenuItem = (MenuItem)objectRegistry.findObject(message.readObjectId());
        removeMenuItem(removeMenuItemMenuItem);
        break;
      case removeAllMenuItemsId:
        removeAllMenuItems();
        break;
      default:
        super.handleMethodCall(methodId, message);
    }
  }
}
