/*
 * Copyright (c) 2000-2002, Shayne R Flint
 * All rights reserved.
 * 
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *    * Redistributions of source code must retain the above copyright
 *      notice, this list of conditions and the following disclaimer.
 *
 *    * Redistributions in binary form must reproduce the above copyright
 *      notice, this list of conditions and the following disclaimer in the
 *      documentation and/or other materials provided with the distribution.
 *
 *    * The name of the author may not be used to endorse or promote products
 *      derived from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
 * IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
 * OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
 * IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
 * NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
 * THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/*
 * ./armidale/api/gui/impl/clientserver/ProgressBarServerImpl.java
 * Generated by armidale.utilities.makeclass.Main armidale v0.9.5 on 10Apr2002 at 17:58:15
 *
 */

package armidale.api.gui.impl.clientserver;

  import armidale.api.context.clientserver.*;
  import armidale.api.gui.ProgressBarFactory;
  import armidale.api.gui.constants.Orientation;
  import java.io.IOException;

public class ProgressBarServerImpl extends WidgetServerImpl implements ProgressBarClientServerIds {

  // readable attributes
  //
  protected int minimum = DEFAULT_MINIMUM;
  protected int maximum = DEFAULT_MAXIMUM;
  protected int value = DEFAULT_VALUE;
  protected boolean drawProgressString = DEFAULT_DRAWPROGRESSSTRING;
  protected int orientation = DEFAULT_ORIENTATION;

  // constructor
  //
  public ProgressBarServerImpl(ServerContext context) {
    super(context);
  }

  // Class ID
  //
  public int getClassId() {
    return ProgressBarFactory.CLASS_ID;
  }

  // attribute set/get/is methods
  //

  public int getMinimum() {
    return minimum;
  }

  public void setMinimum(int minimum) {
    this.minimum = minimum;
    Message msg = new SetAttributeMessage(this.getId(), minimumId);
    msg.writeInt(minimum);
    transport.writeMessage(msg);
  }

  public int getMaximum() {
    return maximum;
  }

  public void setMaximum(int maximum) {
    this.maximum = maximum;
    Message msg = new SetAttributeMessage(this.getId(), maximumId);
    msg.writeInt(maximum);
    transport.writeMessage(msg);
  }

  public int getValue() {
    return value;
  }

  public void setValue(int value) {
    this.value = value;
    Message msg = new SetAttributeMessage(this.getId(), valueId);
    msg.writeInt(value);
    transport.writeMessage(msg);
  }

  public boolean drawsProgressString() {
    return drawProgressString;
  }

  public void setDrawProgressString(boolean drawProgressString) {
    this.drawProgressString = drawProgressString;
    Message msg = new SetAttributeMessage(this.getId(), drawProgressStringId);
    msg.writeBoolean(drawProgressString);
    transport.writeMessage(msg);
  }

  public int getOrientation() {
    return orientation;
  }

  public void setOrientation(int orientation) {
    this.orientation = orientation;
    Message msg = new SetAttributeMessage(this.getId(), orientationId);
    msg.writeInt(orientation);
    transport.writeMessage(msg);
  }

}
