/*
 * Copyright (c) 2000-2002, Shayne R Flint
 * All rights reserved.
 * 
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *    * Redistributions of source code must retain the above copyright
 *      notice, this list of conditions and the following disclaimer.
 *
 *    * Redistributions in binary form must reproduce the above copyright
 *      notice, this list of conditions and the following disclaimer in the
 *      documentation and/or other materials provided with the distribution.
 *
 *    * The name of the author may not be used to endorse or promote products
 *      derived from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
 * IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
 * OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
 * IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
 * NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
 * THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/*
 * ./armidale/api/gui/impl/clientserver/RadioButtonPanelServerImpl.java
 * Generated by armidale.utilities.makeclass.Main armidale v0.9.5 on 10Apr2002 at 17:58:12
 *
 */

package armidale.api.gui.impl.clientserver;

  import armidale.api.context.clientserver.*;
  import armidale.api.gui.RadioButton;
  import armidale.api.gui.RadioButtonPanelCallback;
  import armidale.api.gui.RadioButtonPanelCallbackList;
  import armidale.api.gui.RadioButtonPanelFactory;
  import armidale.api.gui.constants.Orientation;
  import java.io.IOException;
  import java.util.LinkedList;

public class RadioButtonPanelServerImpl extends PanelServerImpl implements RadioButtonPanelClientServerIds {

  // readable attributes
  //
  protected int orientation = DEFAULT_ORIENTATION;

  // Callback object
  //

  protected RadioButtonPanelCallbackList radioButtonPanelCallbackList = new RadioButtonPanelCallbackList();

  // constructor
  //
  public RadioButtonPanelServerImpl(ServerContext context) {
    super(context);
  }

  // Class ID
  //
  public int getClassId() {
    return RadioButtonPanelFactory.CLASS_ID;
  }

  // attribute set/get/is methods
  //

  public int getOrientation() {
    return orientation;
  }

  public void setOrientation(int orientation) {
    this.orientation = orientation;
    Message msg = new SetAttributeMessage(this.getId(), orientationId);
    msg.writeInt(orientation);
    transport.writeMessage(msg);
  }

  // Callback
  //

  public void addRadioButtonPanelCallback(RadioButtonPanelCallback callback) {
    Message msg;
    radioButtonPanelCallbackList.add(callback);
    if (radioButtonPanelCallbackList.size() == 1) {
      msg = new EnableCallbacksMessage(this.getId());
      transport.writeMessage(msg);
    }
  }

  public void removeRadioButtonPanelCallback(RadioButtonPanelCallback callback) {
    Message msg;
    radioButtonPanelCallbackList.remove(callback);
    if (radioButtonPanelCallbackList.size() == 0) {
      msg = new DisableCallbacksMessage(this.getId());
      transport.writeMessage(msg);
    }
  }

  public void removeAllRadioButtonPanelCallbacks() {
    Message msg;
    radioButtonPanelCallbackList.clear();
    msg = new DisableCallbacksMessage(this.getId());
    transport.writeMessage(msg);
  }

  public RadioButtonPanelCallbackList getRadioButtonPanelCallbackList() {
    return radioButtonPanelCallbackList;
  }

  // other methods
  //

  public void addRadioButton(RadioButton radioButton) {
    Message msg = new MethodCallMessage(this.getId(), addRadioButtonRadioButtonId);
    msg.writeObjectId((MessagingObject)radioButton);
    transport.writeMessage(msg);
  }

  public void removeRadioButton(RadioButton radioButton) {
    Message msg = new MethodCallMessage(this.getId(), removeRadioButtonRadioButtonId);
    msg.writeObjectId((MessagingObject)radioButton);
    transport.writeMessage(msg);
  }

  public void removeAllRadioButtons() {
    Message msg = new MethodCallMessage(this.getId(), removeAllRadioButtonsId);
    transport.writeMessage(msg);
  }

  // transport
  //

  public void handleCallback(int callbackMethodId, Message message) {
    int indexSelectedIndex;

    switch (callbackMethodId) {
      case radioButtonPanelIndexSelectedIntId:
        indexSelectedIndex = message.readInt();
        radioButtonPanelCallbackList.indexSelected(this, indexSelectedIndex);
        break;
    }
  }

}
