/*
 * Copyright (c) 2000-2002, Shayne R Flint
 * All rights reserved.
 * 
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *    * Redistributions of source code must retain the above copyright
 *      notice, this list of conditions and the following disclaimer.
 *
 *    * Redistributions in binary form must reproduce the above copyright
 *      notice, this list of conditions and the following disclaimer in the
 *      documentation and/or other materials provided with the distribution.
 *
 *    * The name of the author may not be used to endorse or promote products
 *      derived from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
 * IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
 * OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
 * IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
 * NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
 * THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/*
 * ./armidale/api/gui/impl/clientserver/RadioButtonPanelClientImpl.java
 * Generated by armidale.utilities.makeclass.Main armidale v0.9.5 on 10Apr2002 at 17:58:12
 *
 */

package armidale.api.gui.impl.clientserver;

  import armidale.api.ImplementationException;
  import armidale.api.context.clientserver.*;
  import armidale.api.gui.RadioButton;
  import armidale.api.gui.RadioButtonPanel;
  import armidale.api.gui.RadioButtonPanelCallback;
  import armidale.api.gui.RadioButtonPanelCallbackList;
  import armidale.api.gui.RadioButtonPanelFactory;
  import armidale.api.gui.constants.Orientation;

public class RadioButtonPanelClientImpl extends PanelClientImpl implements RadioButtonPanelClientServerIds {

  // constructor
  //
  public RadioButtonPanelClientImpl(ClientContext context, RadioButtonPanel peer) {
    super(context, peer);
  }

  // Class ID
  //
  public int getClassId() {
    return RadioButtonPanelFactory.CLASS_ID;
  }

  // attribute set/get/is methods
  //

  public int getOrientation() {
    throw new ImplementationException("attribute get/is methods are not supported in client context");
  }

  public void setOrientation(int orientation) {
    ((RadioButtonPanel)peer).setOrientation(orientation);
  }

  // Callback methods
  //

  public void addRadioButtonPanelCallback(RadioButtonPanelCallback callback) {
    ((RadioButtonPanel)peer).addRadioButtonPanelCallback(callback);
  }

  public void removeRadioButtonPanelCallback(RadioButtonPanelCallback callback) {
    ((RadioButtonPanel)peer).removeRadioButtonPanelCallback(callback);
  }

  public void removeAllRadioButtonPanelCallbacks() {
    ((RadioButtonPanel)peer).removeAllRadioButtonPanelCallbacks();
  }

  public RadioButtonPanelCallbackList getRadioButtonPanelCallbackList() {
    throw new ImplementationException("callback get methods are not supported in client context");
  }

  // other methods
  //

  public void addRadioButton(RadioButton radioButton) {
    RadioButton radioButtonPeer;
    if (radioButton==null) {
     radioButtonPeer = null;
    } else {
     radioButtonPeer = (RadioButton)((RadioButtonClientImpl)radioButton).peer;
    }
    ((RadioButtonPanel)peer).addRadioButton(radioButtonPeer);
  }

  public void removeRadioButton(RadioButton radioButton) {
    RadioButton radioButtonPeer;
    if (radioButton==null) {
     radioButtonPeer = null;
    } else {
     radioButtonPeer = (RadioButton)((RadioButtonClientImpl)radioButton).peer;
    }
    ((RadioButtonPanel)peer).removeRadioButton(radioButtonPeer);
  }

  public void removeAllRadioButtons() {
    ((RadioButtonPanel)peer).removeAllRadioButtons();
  }

  // local callback handlers
  //

  private class LocalCallback implements RadioButtonPanelCallback {

    public void indexSelected(RadioButtonPanel radioButtonPanel, int index) {
      Message message = new CallbackMessage(RadioButtonPanelClientImpl.this.getId(), radioButtonPanelIndexSelectedIntId);
      message.writeInt(index);
      transport.writeMessage(message);
    }
  }

  public void handleSetAttribute(int attributeId, Message message) {
    int index;
    int first;
    int count;

    switch (attributeId) {
      case orientationId:
        setOrientation(message.readInt());
        break;
      default:
        super.handleSetAttribute(attributeId, message);
    }
  }

  public void handleMethodCall(int methodId, Message message) {

    // method parameter values
    //
    RadioButton addRadioButtonRadioButton;
    RadioButton removeRadioButtonRadioButton;

    switch (methodId) {
      case addRadioButtonRadioButtonId:
        addRadioButtonRadioButton = (RadioButton)objectRegistry.findObject(message.readObjectId());
        addRadioButton(addRadioButtonRadioButton);
        break;
      case removeRadioButtonRadioButtonId:
        removeRadioButtonRadioButton = (RadioButton)objectRegistry.findObject(message.readObjectId());
        removeRadioButton(removeRadioButtonRadioButton);
        break;
      case removeAllRadioButtonsId:
        removeAllRadioButtons();
        break;
      default:
        super.handleMethodCall(methodId, message);
    }
  }

  public void handleEnableCallbacks() {
    addRadioButtonPanelCallback(new LocalCallback());
  }

  public void handleDisableCallbacks() {
    removeAllRadioButtonPanelCallbacks();
  }
}
