/*
 * Copyright (c) 2000-2002, Shayne R Flint
 * All rights reserved.
 * 
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *    * Redistributions of source code must retain the above copyright
 *      notice, this list of conditions and the following disclaimer.
 *
 *    * Redistributions in binary form must reproduce the above copyright
 *      notice, this list of conditions and the following disclaimer in the
 *      documentation and/or other materials provided with the distribution.
 *
 *    * The name of the author may not be used to endorse or promote products
 *      derived from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
 * IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
 * OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
 * IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
 * NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
 * THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/*
 * ./armidale/api/gui/impl/clientserver/TabbedPanelWidgetClientImpl.java
 * Generated by armidale.utilities.makeclass.Main armidale v0.9.5 on 10Apr2002 at 17:58:31
 *
 */

package armidale.api.gui.impl.clientserver;

  import armidale.api.ImplementationException;
  import armidale.api.context.clientserver.*;
  import armidale.api.gui.Image;
  import armidale.api.gui.TabbedPanelWidget;
  import armidale.api.gui.TabbedPanelWidgetFactory;
  import armidale.api.gui.Widget;
  import armidale.api.impl.clientserver.ArmidaleObjectClientImpl;

public class TabbedPanelWidgetClientImpl extends ArmidaleObjectClientImpl implements TabbedPanelWidgetClientServerIds {

  // constructor
  //
  public TabbedPanelWidgetClientImpl(ClientContext context, TabbedPanelWidget peer) {
    super(context, peer);
  }

  // Class ID
  //
  public int getClassId() {
    return TabbedPanelWidgetFactory.CLASS_ID;
  }

  // attribute set/get/is methods
  //

  public Widget getWidget() {
    throw new ImplementationException("attribute get/is methods are not supported in client context");
  }

  public void setWidget(Widget widget) {
    if (widget==null) {
      ((TabbedPanelWidget)peer).setWidget(null);
    } else {
      ((TabbedPanelWidget)peer).setWidget((Widget)((WidgetClientImpl)widget).peer);
    }
  }

  public String getTitle() {
    throw new ImplementationException("attribute get/is methods are not supported in client context");
  }

  public void setTitle(String title) {
    ((TabbedPanelWidget)peer).setTitle(title);
  }

  public Image getIcon() {
    throw new ImplementationException("attribute get/is methods are not supported in client context");
  }

  public void setIcon(Image icon) {
    if (icon==null) {
      ((TabbedPanelWidget)peer).setIcon(null);
    } else {
      ((TabbedPanelWidget)peer).setIcon((Image)((ImageClientImpl)icon).peer);
    }
  }

  public void handleSetAttribute(int attributeId, Message message) {
    int index;
    int first;
    int count;

    switch (attributeId) {
      case widgetId:
        setWidget((Widget)objectRegistry.findObject(message.readObjectId()));
        break;
      case titleId:
        setTitle(message.readString());
        break;
      case iconId:
        setIcon((Image)objectRegistry.findObject(message.readObjectId()));
        break;
      default:
        super.handleSetAttribute(attributeId, message);
    }
  }
}
