/*
 * Copyright (c) 2000-2002, Shayne R Flint
 * All rights reserved.
 * 
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *    * Redistributions of source code must retain the above copyright
 *      notice, this list of conditions and the following disclaimer.
 *
 *    * Redistributions in binary form must reproduce the above copyright
 *      notice, this list of conditions and the following disclaimer in the
 *      documentation and/or other materials provided with the distribution.
 *
 *    * The name of the author may not be used to endorse or promote products
 *      derived from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
 * IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
 * OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
 * IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
 * NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
 * THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/*
 * ./armidale/api/gui/impl/clientserver/TableServerImpl.java
 * Generated by armidale.utilities.makeclass.Main armidale v0.9.5 on 10Apr2002 at 17:58:16
 *
 */

package armidale.api.gui.impl.clientserver;

  import armidale.api.context.clientserver.*;
  import armidale.api.gui.TableCallback;
  import armidale.api.gui.TableCallbackList;
  import armidale.api.gui.TableData;
  import armidale.api.gui.TableFactory;
  import java.io.IOException;
  import java.util.LinkedList;

public class TableServerImpl extends WidgetServerImpl implements TableClientServerIds {

  // readable attributes
  //
  protected TableData tableData;

  // Callback object
  //

  protected TableCallbackList tableCallbackList = new TableCallbackList();

  // constructor
  //
  public TableServerImpl(ServerContext context) {
    super(context);
  }

  // Class ID
  //
  public int getClassId() {
    return TableFactory.CLASS_ID;
  }

  // attribute set/get/is methods
  //

  public TableData getTableData() {
    return tableData;
  }

  public void setTableData(TableData tableData) {
    this.tableData = tableData;
    Message msg = new SetAttributeMessage(this.getId(), tableDataId);
    msg.writeObjectId((MessagingObject)tableData);
    transport.writeMessage(msg);
  }

  // Callback
  //

  public void addTableCallback(TableCallback callback) {
    Message msg;
    tableCallbackList.add(callback);
    if (tableCallbackList.size() == 1) {
      msg = new EnableCallbacksMessage(this.getId());
      transport.writeMessage(msg);
    }
  }

  public void removeTableCallback(TableCallback callback) {
    Message msg;
    tableCallbackList.remove(callback);
    if (tableCallbackList.size() == 0) {
      msg = new DisableCallbacksMessage(this.getId());
      transport.writeMessage(msg);
    }
  }

  public void removeAllTableCallbacks() {
    Message msg;
    tableCallbackList.clear();
    msg = new DisableCallbacksMessage(this.getId());
    transport.writeMessage(msg);
  }

  public TableCallbackList getTableCallbackList() {
    return tableCallbackList;
  }

  // transport
  //

  public void handleCallback(int callbackMethodId, Message message) {
    int[] rowsSelectedIndices;

    switch (callbackMethodId) {
      case tableRowsSelectedIntId:
        rowsSelectedIndices = new int[message.readInt()];
        for (int i=0; i < rowsSelectedIndices.length; i++) {
          rowsSelectedIndices[i] = message.readInt();
        }
        tableCallbackList.rowsSelected(this, rowsSelectedIndices);
        break;
    }
  }

}
