/*
 * Copyright (c) 2000-2002, Shayne R Flint
 * All rights reserved.
 * 
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *    * Redistributions of source code must retain the above copyright
 *      notice, this list of conditions and the following disclaimer.
 *
 *    * Redistributions in binary form must reproduce the above copyright
 *      notice, this list of conditions and the following disclaimer in the
 *      documentation and/or other materials provided with the distribution.
 *
 *    * The name of the author may not be used to endorse or promote products
 *      derived from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
 * IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
 * OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
 * IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
 * NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
 * THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/*
 * ./armidale/api/gui/impl/clientserver/TextServerImpl.java
 * Generated by armidale.utilities.makeclass.Main armidale v0.9.5 on 10Apr2002 at 17:58:21
 *
 */

package armidale.api.gui.impl.clientserver;

  import armidale.api.context.clientserver.*;
  import armidale.api.gui.TextCallback;
  import armidale.api.gui.TextCallbackList;
  import java.io.IOException;
  import java.util.LinkedList;

public abstract class TextServerImpl extends WidgetServerImpl implements TextClientServerIds {

  // readable attributes
  //
  protected String text = DEFAULT_TEXT;
  protected boolean editable = DEFAULT_EDITABLE;

  // Callback object
  //

  protected TextCallbackList textCallbackList = new TextCallbackList();

  // constructor
  //
  public TextServerImpl(ServerContext context) {
    super(context);
    setBackgroundColor(DEFAULT_TEXT_BACKGROUNDCOLOR);
  }

  // attribute set/get/is methods
  //

  public String getText() {
    return text;
  }

  public void setText(String text) {
    this.text = text;
    Message msg = new SetAttributeMessage(this.getId(), textId);
    msg.writeString(text);
    transport.writeMessage(msg);
  }

  public boolean isEditable() {
    return editable;
  }

  public void setEditable(boolean editable) {
    this.editable = editable;
    Message msg = new SetAttributeMessage(this.getId(), editableId);
    msg.writeBoolean(editable);
    transport.writeMessage(msg);
  }

  // Callback
  //

  public void addTextCallback(TextCallback callback) {
    Message msg;
    textCallbackList.add(callback);
    if (textCallbackList.size() == 1) {
      msg = new EnableCallbacksMessage(this.getId());
      transport.writeMessage(msg);
    }
  }

  public void removeTextCallback(TextCallback callback) {
    Message msg;
    textCallbackList.remove(callback);
    if (textCallbackList.size() == 0) {
      msg = new DisableCallbacksMessage(this.getId());
      transport.writeMessage(msg);
    }
  }

  public void removeAllTextCallbacks() {
    Message msg;
    textCallbackList.clear();
    msg = new DisableCallbacksMessage(this.getId());
    transport.writeMessage(msg);
  }

  public TextCallbackList getTextCallbackList() {
    return textCallbackList;
  }

  // transport
  //

  public void handleCallback(int callbackMethodId, Message message) {
    String textChangedTheText;

    switch (callbackMethodId) {
      case textTextChangedStringId:
        textChangedTheText = message.readString();
        textCallbackList.textChanged(this, textChangedTheText);
        break;
    }
  }

}
