/*
 * Copyright (c) 2000-2002, Shayne R Flint
 * All rights reserved.
 * 
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *    * Redistributions of source code must retain the above copyright
 *      notice, this list of conditions and the following disclaimer.
 *
 *    * Redistributions in binary form must reproduce the above copyright
 *      notice, this list of conditions and the following disclaimer in the
 *      documentation and/or other materials provided with the distribution.
 *
 *    * The name of the author may not be used to endorse or promote products
 *      derived from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
 * IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
 * OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
 * IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
 * NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
 * THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/*
 * ./armidale/api/gui/impl/clientserver/ToggleClientImpl.java
 * Generated by armidale.utilities.makeclass.Main armidale v0.9.5 on 10Apr2002 at 17:57:57
 *
 */

package armidale.api.gui.impl.clientserver;

  import armidale.api.ImplementationException;
  import armidale.api.context.clientserver.*;
  import armidale.api.gui.Toggle;
  import armidale.api.gui.ToggleCallback;
  import armidale.api.gui.ToggleCallbackList;

public abstract class ToggleClientImpl extends ButtonClientImpl implements ToggleClientServerIds {

  // constructor
  //
  public ToggleClientImpl(ClientContext context, Toggle peer) {
    super(context, peer);
  }

  // attribute set/get/is methods
  //

  public boolean isSelected() {
    throw new ImplementationException("attribute get/is methods are not supported in client context");
  }

  public void setSelected(boolean selected) {
    ((Toggle)peer).setSelected(selected);
  }

  // Callback methods
  //

  public void addToggleCallback(ToggleCallback callback) {
    ((Toggle)peer).addToggleCallback(callback);
  }

  public void removeToggleCallback(ToggleCallback callback) {
    ((Toggle)peer).removeToggleCallback(callback);
  }

  public void removeAllToggleCallbacks() {
    ((Toggle)peer).removeAllToggleCallbacks();
  }

  public ToggleCallbackList getToggleCallbackList() {
    throw new ImplementationException("callback get methods are not supported in client context");
  }

  // local callback handlers
  //

  private class LocalCallback implements ToggleCallback {

    public void stateChange(Toggle toggle, boolean selected) {
      Message message = new CallbackMessage(ToggleClientImpl.this.getId(), toggleStateChangeBooleanId);
      message.writeBoolean(selected);
      transport.writeMessage(message);
    }
  }

  public void handleSetAttribute(int attributeId, Message message) {
    int index;
    int first;
    int count;

    switch (attributeId) {
      case selectedId:
        setSelected(message.readBoolean());
        break;
      default:
        super.handleSetAttribute(attributeId, message);
    }
  }

  public void handleEnableCallbacks() {
    addToggleCallback(new LocalCallback());
  }

  public void handleDisableCallbacks() {
    removeAllToggleCallbacks();
  }
}
