/*
 * Copyright (c) 2000-2002, Shayne R Flint
 * All rights reserved.
 * 
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *    * Redistributions of source code must retain the above copyright
 *      notice, this list of conditions and the following disclaimer.
 *
 *    * Redistributions in binary form must reproduce the above copyright
 *      notice, this list of conditions and the following disclaimer in the
 *      documentation and/or other materials provided with the distribution.
 *
 *    * The name of the author may not be used to endorse or promote products
 *      derived from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
 * IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
 * OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
 * IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
 * NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
 * THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/*
 * ./armidale/api/gui/impl/clientserver/VisibleObjectClientImpl.java
 * Generated by armidale.utilities.makeclass.Main armidale v0.9.5 on 10Apr2002 at 17:57:43
 *
 */

package armidale.api.gui.impl.clientserver;

  import armidale.api.ImplementationException;
  import armidale.api.context.clientserver.*;
  import armidale.api.gui.Position;
  import armidale.api.gui.VisibleObject;
  import armidale.api.gui.VisibleObjectCallback;
  import armidale.api.gui.VisibleObjectCallbackList;
  import armidale.api.impl.clientserver.ArmidaleObjectClientImpl;

public abstract class VisibleObjectClientImpl extends ArmidaleObjectClientImpl implements VisibleObjectClientServerIds {

  // constructor
  //
  public VisibleObjectClientImpl(ClientContext context, VisibleObject peer) {
    super(context, peer);
  }

  // attribute set/get/is methods
  //

  public boolean isVisible() {
    throw new ImplementationException("attribute get/is methods are not supported in client context");
  }

  public void setVisible(boolean visible) {
    ((VisibleObject)peer).setVisible(visible);
  }

  // Callback methods
  //

  public void addVisibleObjectCallback(VisibleObjectCallback callback) {
    ((VisibleObject)peer).addVisibleObjectCallback(callback);
  }

  public void removeVisibleObjectCallback(VisibleObjectCallback callback) {
    ((VisibleObject)peer).removeVisibleObjectCallback(callback);
  }

  public void removeAllVisibleObjectCallbacks() {
    ((VisibleObject)peer).removeAllVisibleObjectCallbacks();
  }

  public VisibleObjectCallbackList getVisibleObjectCallbackList() {
    throw new ImplementationException("callback get methods are not supported in client context");
  }

  // other methods
  //

  public void show() {
    ((VisibleObject)peer).show();
  }

  public void hide() {
    ((VisibleObject)peer).hide();
  }

  public void refresh() {
    ((VisibleObject)peer).refresh();
  }

  // local callback handlers
  //

  private class LocalCallback implements VisibleObjectCallback {

    public void objectMoved(VisibleObject visibleObject, Position position) {
      Message message = new CallbackMessage(VisibleObjectClientImpl.this.getId(), visibleObjectObjectMovedPositionId);
      message.writePosition(position);
      transport.writeMessage(message);
    }
  }

  public void handleSetAttribute(int attributeId, Message message) {
    int index;
    int first;
    int count;

    switch (attributeId) {
      case visibleId:
        setVisible(message.readBoolean());
        break;
      default:
        super.handleSetAttribute(attributeId, message);
    }
  }

  public void handleMethodCall(int methodId, Message message) {

    // method parameter values
    //

    switch (methodId) {
      case showId:
        show();
        break;
      case hideId:
        hide();
        break;
      case refreshId:
        refresh();
        break;
      default:
        super.handleMethodCall(methodId, message);
    }
  }

  public void handleEnableCallbacks() {
    addVisibleObjectCallback(new LocalCallback());
  }

  public void handleDisableCallbacks() {
    removeAllVisibleObjectCallbacks();
  }
}
